using System.Globalization;
using System.Text.RegularExpressions;
using IvaoHub.Core.Services;
using Microsoft.Extensions.Options;

namespace IvaoHub.Core.Content;

/// <summary>
/// Where an uploaded file goes and how it comes back. One place, so that "the name on disk is
/// opaque" and "a stored name can never leave its own folder" are properties of the hub rather
/// than of whoever wrote the last endpoint (design M1 section 2).
/// </summary>
public sealed partial class MediaStorage
{
    private readonly string _root;

    public MediaStorage(HubPaths paths, IOptions<MediaOptions> options)
    {
        ArgumentNullException.ThrowIfNull(paths);
        ArgumentNullException.ThrowIfNull(options);

        _root = string.IsNullOrWhiteSpace(options.Value.Directory)
            ? paths.Media
            : Path.GetFullPath(options.Value.Directory);
    }

    /// <summary>
    /// A stored name, and the only shape this class will ever open: year, month, thirty two hex
    /// characters and a suffix. It is checked on the way in and again on the way out, because the
    /// value travels through a database column and a column is not a promise.
    /// </summary>
    [GeneratedRegex(@"^[0-9]{4}/[0-9]{2}/[0-9a-f]{32}(\.[a-z0-9]{1,8})?$")]
    private static partial Regex StoredNamePattern { get; }

    /// <summary>
    /// Writes the bytes under a name of our own making and answers with it. The name carries the
    /// year and the month so that one folder never holds tens of thousands of entries, and its
    /// last part is a fresh identifier: two departments uploading <c>logo.png</c> get two files,
    /// and nothing a person typed becomes a path.
    /// </summary>
    public async Task<string> SaveAsync(Stream content, MediaFormat format, DateTime nowUtc, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(content);
        ArgumentNullException.ThrowIfNull(format);

        var folder = nowUtc.ToString("yyyy/MM", CultureInfo.InvariantCulture);
        var storedName = $"{folder}/{Guid.NewGuid():N}{format.Extension}";

        var path = Resolve(storedName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using (var file = File.Create(path))
        {
            await content.CopyToAsync(file, cancellationToken);
        }

        return storedName;
    }

    /// <summary>The file itself, or null when the row outlived it.</summary>
    public FileInfo? Find(string storedName)
    {
        if (!StoredNamePattern.IsMatch(storedName ?? string.Empty))
        {
            return null;
        }

        var file = new FileInfo(Resolve(storedName!));
        return file.Exists ? file : null;
    }

    /// <summary>Removes the file. Says whether there was one, so a caller can be honest about it.</summary>
    public bool Delete(string storedName)
    {
        var file = Find(storedName);
        if (file is null)
        {
            return false;
        }

        file.Delete();
        return true;
    }

    private string Resolve(string storedName)
    {
        if (!StoredNamePattern.IsMatch(storedName))
        {
            throw new InvalidOperationException("A stored media name is generated by this class and has a fixed shape.");
        }

        return Path.Combine(_root, storedName.Replace('/', Path.DirectorySeparatorChar));
    }
}
