using System.Buffers;
using System.Globalization;
using System.Security.Cryptography;
using System.Text.RegularExpressions;
using IvaoHub.Core.Services;
using Microsoft.Extensions.Options;

namespace IvaoHub.Core.Content;

/// <summary>
/// What a save answers: the opaque name the bytes went under, and their SHA-256 in lower case hex
/// — the fingerprint an upload is compared by (decision note of 12 September 2026).
/// </summary>
public sealed record StoredFile(string StoredName, string Sha256);

/// <summary>
/// Where an uploaded file goes and how it comes back. One place, so that "the name on disk is
/// opaque" and "a stored name can never leave its own folder" are properties of the hub rather
/// than of whoever wrote the last endpoint (design M1 section 2).
/// </summary>
public sealed partial class MediaStorage
{
    private readonly string _root;

    public MediaStorage(HubPaths paths, IOptions<MediaOptions> options)
    {
        ArgumentNullException.ThrowIfNull(paths);
        ArgumentNullException.ThrowIfNull(options);

        _root = string.IsNullOrWhiteSpace(options.Value.Directory)
            ? paths.Media
            : Path.GetFullPath(options.Value.Directory);
    }

    /// <summary>
    /// A stored name, and the only shape this class will ever open: year, month, thirty two hex
    /// characters and a suffix. It is checked on the way in and again on the way out, because the
    /// value travels through a database column and a column is not a promise.
    /// </summary>
    [GeneratedRegex(@"^[0-9]{4}/[0-9]{2}/[0-9a-f]{32}(\.[a-z0-9]{1,8})?$")]
    private static partial Regex StoredNamePattern { get; }

    /// <summary>
    /// Writes the bytes under a name of our own making and answers with it. The name carries the
    /// year and the month so that one folder never holds tens of thousands of entries, and its
    /// last part is a fresh identifier: two departments uploading <c>logo.png</c> get two files,
    /// and nothing a person typed becomes a path.
    /// </summary>
    public async Task<StoredFile> SaveAsync(Stream content, MediaFormat format, DateTime nowUtc, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(content);
        ArgumentNullException.ThrowIfNull(format);

        var folder = nowUtc.ToString("yyyy/MM", CultureInfo.InvariantCulture);
        var storedName = $"{folder}/{Guid.NewGuid():N}{format.Extension}";

        var path = Resolve(storedName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // The fingerprint is taken in the same pass as the copy: the bytes go by once, and reading
        // the file back to hash it would be a second pass for nothing.
        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        var buffer = ArrayPool<byte>.Shared.Rent(81920);

        try
        {
            await using var file = File.Create(path);

            int read;
            while ((read = await content.ReadAsync(buffer, cancellationToken)) > 0)
            {
                hash.AppendData(buffer, 0, read);
                await file.WriteAsync(buffer.AsMemory(0, read), cancellationToken);
            }
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(buffer);
        }

        return new StoredFile(storedName, Convert.ToHexStringLower(hash.GetHashAndReset()));
    }

    /// <summary>The file itself, or null when the row outlived it.</summary>
    public FileInfo? Find(string storedName)
    {
        if (!StoredNamePattern.IsMatch(storedName ?? string.Empty))
        {
            return null;
        }

        var file = new FileInfo(Resolve(storedName!));
        return file.Exists ? file : null;
    }

    /// <summary>Removes the file. Says whether there was one, so a caller can be honest about it.</summary>
    public bool Delete(string storedName)
    {
        var file = Find(storedName);
        if (file is null)
        {
            return false;
        }

        file.Delete();
        return true;
    }

    private string Resolve(string storedName)
    {
        if (!StoredNamePattern.IsMatch(storedName))
        {
            throw new InvalidOperationException("A stored media name is generated by this class and has a fixed shape.");
        }

        return Path.Combine(_root, storedName.Replace('/', Path.DirectorySeparatorChar));
    }
}
