// <auto-generated />
using System;
using IvaoHub.Modules.Training.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaoHub.Modules.Training.Data.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20260926101057_AddSheetItems")]
    partial class AddSheetItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IvaoHub.Core.Content.AwardSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_cms_award_signals");

                    b.HasIndex("Vid", "Status")
                        .HasDatabaseName("ix_cms_award_signals_vid_status");

                    b.HasIndex("SourceModule", "SourceId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_award_signals_source_module_source_id_vid");

                    b.ToTable("cms_award_signals", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_calendar_entries");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_starts_at_utc");

                    b.HasIndex("OwnerDepartment", "StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_owner_department_starts_at_utc");

                    b.HasIndex("SourceModule", "SourceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_calendar_entries_source_module_source_id_sequence");

                    b.ToTable("cms_calendar_entries", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("general")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("participants_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cms_contact_messages");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("ix_cms_contact_messages_created_by_created_at");

                    b.HasIndex("OwnerDepartment", "Status", "CreatedAt")
                        .HasDatabaseName("ix_cms_contact_messages_owner_department_status_created_at");

                    b.HasIndex("SourceModule", "SourceId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_contact_messages_source_module_source_id_kind");

                    b.ToTable("cms_contact_messages", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("label_i18n");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.HasKey("Id")
                        .HasName("pk_cms_contact_references");

                    b.HasIndex("SourceModule", "SourceId")
                        .HasDatabaseName("ix_cms_contact_references_source_module_source_id");

                    b.HasIndex("MessageId", "SourceModule", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_contact_references_message_id_source_module_source_id");

                    b.ToTable("cms_contact_references", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.MediaUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime?>("UsedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_until");

                    b.HasKey("Id")
                        .HasName("pk_cms_media_uses");

                    b.HasIndex("MediaId", "UsedUntil")
                        .HasDatabaseName("ix_cms_media_uses_media_id_used_until");

                    b.HasIndex("SourceModule", "SourceId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_media_uses_source_module_source_id_media_id");

                    b.ToTable("cms_media_uses", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.SearchIndexEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_search_index");

                    b.HasIndex("Locale", "UpdatedAt")
                        .HasDatabaseName("ix_cms_search_index_locale_updated_at");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("ix_cms_search_index_fulltext")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex("SourceModule", "SourceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_search_index_source_module_source_id_locale");

                    b.ToTable("cms_search_index", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Services.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("json")
                        .HasColumnName("after_json");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("json")
                        .HasColumnName("before_json");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_superadmin");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_hub_audit_log");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_hub_audit_log_entity_entity_id");

                    b.HasIndex("Vid", "At")
                        .HasDatabaseName("ix_hub_audit_log_vid_at");

                    b.ToTable("hub_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Modules.Training.Sheets.SheetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("section");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_trn_sheet_items");

                    b.HasIndex("Kind", "Rating", "Sort")
                        .HasDatabaseName("ix_trn_sheet_items_kind_rating_sort");

                    b.ToTable("trn_sheet_items", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactReference", b =>
                {
                    b.HasOne("IvaoHub.Core.Content.ContactMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cms_contact_references_cms_contact_messages_message_id");

                    b.Navigation("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
