// <auto-generated />
using System;
using IvaoHub.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaoHub.Core.Data.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IvaoHub.Core.Auth.HubUser", b =>
                {
                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("discord_id");

                    b.Property<string>("DivisionCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("division_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_staff");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_superadmin");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("Locale")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("PublicNickname")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("public_nickname");

                    b.Property<int?>("RatingAtc")
                        .HasColumnType("int")
                        .HasColumnName("rating_atc");

                    b.Property<int?>("RatingPilot")
                        .HasColumnType("int")
                        .HasColumnName("rating_pilot");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Vid")
                        .HasName("pk_hub_users");

                    b.HasIndex("IsStaff")
                        .HasDatabaseName("ix_hub_users_is_staff");

                    b.ToTable("hub_users", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("department");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("effect");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("suspended_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("value");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_hub_user_grants");

                    b.HasIndex("Vid", "Effect")
                        .HasDatabaseName("ix_hub_user_grants_vid_effect");

                    b.ToTable("hub_user_grants", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserStaffPosition", b =>
                {
                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.Property<string>("Position")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("position");

                    b.Property<string>("Department")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("department");

                    b.Property<string>("Fir")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("fir");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("level");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.HasKey("Vid", "Position")
                        .HasName("pk_hub_user_staff_positions");

                    b.HasIndex("Department")
                        .HasDatabaseName("ix_hub_user_staff_positions_department");

                    b.ToTable("hub_user_staff_positions", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserToken", b =>
                {
                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.Property<string>("AccessTokenEnc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_enc");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_enc");

                    b.Property<string>("Scopes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("scopes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Vid")
                        .HasName("pk_hub_user_tokens");

                    b.ToTable("hub_user_tokens", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.AwardSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_cms_award_signals");

                    b.HasIndex("Vid", "Status")
                        .HasDatabaseName("ix_cms_award_signals_vid_status");

                    b.HasIndex("SourceModule", "SourceId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_award_signals_source_module_source_id_vid");

                    b.ToTable("cms_award_signals", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_calendar_entries");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_starts_at_utc");

                    b.HasIndex("OwnerDepartment", "StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_owner_department_starts_at_utc");

                    b.HasIndex("SourceModule", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_calendar_entries_source_module_source_id");

                    b.ToTable("cms_calendar_entries", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContentEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("body_json");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("category");

                    b.Property<long?>("CoverMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_media_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<long?>("FileMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_media_id");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_template");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("owner_department");

                    b.Property<bool>("Pinned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pinned");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<long?>("PublishedVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("published_version_id");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("schema_version");

                    b.Property<string>("Seo")
                        .HasColumnType("json")
                        .HasColumnName("seo_i18n");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("slug");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("json")
                        .HasColumnName("summary_i18n");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_contents");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_cms_contents_template_id");

                    b.HasIndex("Kind", "Status")
                        .HasDatabaseName("ix_cms_contents_kind_status");

                    b.HasIndex("OwnerDepartment", "Status")
                        .HasDatabaseName("ix_cms_contents_owner_department_status");

                    b.HasIndex("Kind", "Slug", "IsTemplate")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_contents_kind_slug_is_template");

                    b.ToTable("cms_contents", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContentVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("body_json");

                    b.Property<string>("Changelog")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("changelog");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<int>("PublishedBy")
                        .HasColumnType("int")
                        .HasColumnName("published_by");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("schema_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cms_content_versions");

                    b.HasIndex("ContentId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_content_versions_content_id_version");

                    b.ToTable("cms_content_versions", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("owner_department");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_links");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_cms_links_category");

                    b.HasIndex("OwnerDepartment", "IsActive")
                        .HasDatabaseName("ix_cms_links_owner_department_is_active");

                    b.ToTable("cms_links", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.SearchIndexEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_search_index");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("ix_cms_search_index_fulltext")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex("SourceModule", "SourceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_search_index_source_module_source_id_locale");

                    b.ToTable("cms_search_index", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Division.DivisionSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("value_json");

                    b.HasKey("Key")
                        .HasName("pk_hub_division_settings");

                    b.ToTable("hub_division_settings", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Ivao.IvaoAirport", b =>
                {
                    b.Property<string>("Icao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao");

                    b.Property<string>("CenterId")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("center_id");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("raw_json");

                    b.Property<string>("RunwaysJson")
                        .HasColumnType("json")
                        .HasColumnName("runways_json");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.HasKey("Icao")
                        .HasName("pk_ref_ivao_airports");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("ix_ref_ivao_airports_center_id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_ref_ivao_airports_country_id");

                    b.ToTable("ref_ivao_airports", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Ivao.IvaoCenter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("id");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("raw_json");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_ref_ivao_centers");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_ref_ivao_centers_country_id");

                    b.ToTable("ref_ivao_centers", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Services.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("json")
                        .HasColumnName("after_json");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("json")
                        .HasColumnName("before_json");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_superadmin");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_hub_audit_log");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_hub_audit_log_entity_entity_id");

                    b.HasIndex("Vid", "At")
                        .HasDatabaseName("ix_hub_audit_log_vid_at");

                    b.ToTable("hub_audit_log", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Services.JobLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("job");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_hub_jobs_log");

                    b.HasIndex("Job", "StartedAt")
                        .HasDatabaseName("ix_hub_jobs_log_job_started_at");

                    b.ToTable("hub_jobs_log", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserGrant", b =>
                {
                    b.HasOne("IvaoHub.Core.Auth.HubUser", "User")
                        .WithMany()
                        .HasForeignKey("Vid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hub_user_grants_hub_users_vid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserStaffPosition", b =>
                {
                    b.HasOne("IvaoHub.Core.Auth.HubUser", "User")
                        .WithMany("StaffPositions")
                        .HasForeignKey("Vid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hub_user_staff_positions_hub_users_vid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.UserToken", b =>
                {
                    b.HasOne("IvaoHub.Core.Auth.HubUser", "User")
                        .WithOne()
                        .HasForeignKey("IvaoHub.Core.Auth.UserToken", "Vid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hub_user_tokens_hub_users_vid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContentVersion", b =>
                {
                    b.HasOne("IvaoHub.Core.Content.ContentEntry", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cms_content_versions_cms_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("IvaoHub.Core.Auth.HubUser", b =>
                {
                    b.Navigation("StaffPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
