// <auto-generated />
using System;
using IvaoHub.Modules.FlightOps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaoHub.Modules.FlightOps.Data.Migrations
{
    [DbContext(typeof(FlightOpsDbContext))]
    [Migration("20260916175155_AddTours")]
    partial class AddTours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IvaoHub.Core.Content.AwardSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_cms_award_signals");

                    b.HasIndex("Vid", "Status")
                        .HasDatabaseName("ix_cms_award_signals_vid_status");

                    b.HasIndex("SourceModule", "SourceId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_award_signals_source_module_source_id_vid");

                    b.ToTable("cms_award_signals", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_calendar_entries");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_starts_at_utc");

                    b.HasIndex("OwnerDepartment", "StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_owner_department_starts_at_utc");

                    b.HasIndex("SourceModule", "SourceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_calendar_entries_source_module_source_id_sequence");

                    b.ToTable("cms_calendar_entries", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.MediaUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime?>("UsedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_until");

                    b.HasKey("Id")
                        .HasName("pk_cms_media_uses");

                    b.HasIndex("MediaId", "UsedUntil")
                        .HasDatabaseName("ix_cms_media_uses_media_id_used_until");

                    b.HasIndex("SourceModule", "SourceId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_media_uses_source_module_source_id_media_id");

                    b.ToTable("cms_media_uses", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.SearchIndexEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_search_index");

                    b.HasIndex("Locale", "UpdatedAt")
                        .HasDatabaseName("ix_cms_search_index_locale_updated_at");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("ix_cms_search_index_fulltext")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex("SourceModule", "SourceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_search_index_source_module_source_id_locale");

                    b.ToTable("cms_search_index", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Aircraft.AircraftGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("IcaoTypesJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("icao_types_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("name_i18n");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_aircraft_groups");

                    b.ToTable("fo_aircraft_groups", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Aircraft.AircraftProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CruiseTasKt")
                        .HasColumnType("int")
                        .HasColumnName("cruise_tas_kt");

                    b.Property<string>("IcaoType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao_type");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("note");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_aircraft_profiles");

                    b.HasIndex("IcaoType")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_aircraft_profiles_icao_type");

                    b.ToTable("fo_aircraft_profiles", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Tours.Tour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedAircraftJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("allowed_aircraft_json");

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<long?>("BannerMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("banner_media_id");

                    b.Property<string>("BriefingJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("briefing_json");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("close_at");

                    b.Property<long?>("CoverMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_media_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("DailyLegLimit")
                        .HasColumnType("int")
                        .HasColumnName("daily_leg_limit");

                    b.Property<string>("HubRotationOrder")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("hub_rotation_order");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_template");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<int?>("MinPilotRating")
                        .HasColumnType("int")
                        .HasColumnName("min_pilot_rating");

                    b.Property<string>("OpenGoal")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("open_goal");

                    b.Property<string>("OpenGoalJson")
                        .HasColumnType("json")
                        .HasColumnName("open_goal_json");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<long?>("ParentTourId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_tour_id");

                    b.Property<string>("Progression")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("progression");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("ReferenceAircraftIcao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("reference_aircraft_icao");

                    b.Property<DateTime?>("ReleaseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_at");

                    b.Property<int>("ReportWindowDays")
                        .HasColumnType("int")
                        .HasColumnName("report_window_days");

                    b.Property<int?>("RequiredNm")
                        .HasColumnType("int")
                        .HasColumnName("required_nm");

                    b.Property<int?>("RequiredSubtours")
                        .HasColumnType("int")
                        .HasColumnName("required_subtours");

                    b.Property<bool>("RequiresProcedures")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_procedures");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("ShowPreview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_preview");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("summary_i18n");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_fo_tours");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_tours_slug");

                    b.HasIndex("IsTemplate", "ReleaseAt")
                        .HasDatabaseName("ix_fo_tours_is_template_release_at");

                    b.ToTable("fo_tours", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
