// <auto-generated />
using System;
using IvaoHub.Modules.FlightOps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaoHub.Modules.FlightOps.Data.Migrations
{
    [DbContext(typeof(FlightOpsDbContext))]
    [Migration("20260923095343_AddAtcArchiveAvailable")]
    partial class AddAtcArchiveAvailable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IvaoHub.Core.Content.AwardSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_cms_award_signals");

                    b.HasIndex("Vid", "Status")
                        .HasDatabaseName("ix_cms_award_signals_vid_status");

                    b.HasIndex("SourceModule", "SourceId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_award_signals_source_module_source_id_vid");

                    b.ToTable("cms_award_signals", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_calendar_entries");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_starts_at_utc");

                    b.HasIndex("OwnerDepartment", "StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_owner_department_starts_at_utc");

                    b.HasIndex("SourceModule", "SourceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_calendar_entries_source_module_source_id_sequence");

                    b.ToTable("cms_calendar_entries", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.MediaUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime?>("UsedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_until");

                    b.HasKey("Id")
                        .HasName("pk_cms_media_uses");

                    b.HasIndex("MediaId", "UsedUntil")
                        .HasDatabaseName("ix_cms_media_uses_media_id_used_until");

                    b.HasIndex("SourceModule", "SourceId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_media_uses_source_module_source_id_media_id");

                    b.ToTable("cms_media_uses", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.SearchIndexEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_search_index");

                    b.HasIndex("Locale", "UpdatedAt")
                        .HasDatabaseName("ix_cms_search_index_locale_updated_at");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("ix_cms_search_index_fulltext")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex("SourceModule", "SourceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_search_index_source_module_source_id_locale");

                    b.ToTable("cms_search_index", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Aircraft.AircraftGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("IcaoTypesJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("icao_types_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("name_i18n");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_aircraft_groups");

                    b.ToTable("fo_aircraft_groups", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Aircraft.AircraftProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CruiseTasKt")
                        .HasColumnType("int")
                        .HasColumnName("cruise_tas_kt");

                    b.Property<string>("IcaoType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao_type");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("note");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_aircraft_profiles");

                    b.HasIndex("IcaoType")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_aircraft_profiles_icao_type");

                    b.ToTable("fo_aircraft_profiles", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Legs.Leg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AircraftJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("aircraft_json");

                    b.Property<string>("ArrivalIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arrival_icao");

                    b.Property<double>("ArrivalLatitude")
                        .HasColumnType("double")
                        .HasColumnName("arrival_latitude");

                    b.Property<double>("ArrivalLongitude")
                        .HasColumnType("double")
                        .HasColumnName("arrival_longitude");

                    b.Property<string>("CallsignsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("callsigns_json");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartureIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("departure_icao");

                    b.Property<double>("DepartureLatitude")
                        .HasColumnType("double")
                        .HasColumnName("departure_latitude");

                    b.Property<double>("DepartureLongitude")
                        .HasColumnType("double")
                        .HasColumnName("departure_longitude");

                    b.Property<decimal>("DistanceNm")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("distance_nm");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("flight_number");

                    b.Property<string>("FlightNumbersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("flight_numbers_json");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("RealCallsign")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("real_callsign");

                    b.Property<DateTime?>("ReleaseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_at");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retired_at");

                    b.Property<string>("RetiredReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("retired_reason");

                    b.Property<long?>("RotationId")
                        .HasColumnType("bigint")
                        .HasColumnName("rotation_id");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("SeqInRotation")
                        .HasColumnType("int")
                        .HasColumnName("seq_in_rotation");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_legs");

                    b.HasIndex("RotationId")
                        .HasDatabaseName("ix_fo_legs_rotation_id");

                    b.HasIndex("TourId", "Number")
                        .HasDatabaseName("ix_fo_legs_tour_id_number");

                    b.ToTable("fo_legs", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Ban", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<long?>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_fo_bans");

                    b.HasIndex("Vid")
                        .HasDatabaseName("ix_fo_bans_vid");

                    b.ToTable("fo_bans", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Enrolment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_fo_enrolments");

                    b.HasIndex("Vid")
                        .HasDatabaseName("ix_fo_enrolments_vid");

                    b.HasIndex("TourId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_enrolments_tour_id_vid");

                    b.ToTable("fo_enrolments", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Pirep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Approach")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("approach");

                    b.Property<string>("ArrivalIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arrival_icao");

                    b.Property<int?>("AssignedToVid")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_vid");

                    b.Property<bool>("AtcArchiveAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("atc_archive_available");

                    b.Property<string>("AtcContactsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("atc_contacts_json");

                    b.Property<string>("AtcExemptionsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("atc_exemptions_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decided_at");

                    b.Property<int?>("DecidedByVid")
                        .HasColumnType("int")
                        .HasColumnName("decided_by_vid");

                    b.Property<string>("DepartureIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("departure_icao");

                    b.Property<decimal>("DistanceNm")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)")
                        .HasColumnName("distance_nm");

                    b.Property<string>("DiversionIcao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("diversion_icao");

                    b.Property<string>("DiversionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("diversion_note");

                    b.Property<string>("DiversionReason")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("diversion_reason");

                    b.Property<string>("FlightRules")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("flight_rules");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_disputed");

                    b.Property<bool>("IsDiversion")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_diversion");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lease_until");

                    b.Property<long?>("LegId")
                        .HasColumnType("bigint")
                        .HasColumnName("leg_id");

                    b.Property<string>("LegSnapshotJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("leg_snapshot_json");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("PilotRemarks")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("pilot_remarks");

                    b.Property<DateTime?>("ResubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resubmitted_at");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("RulesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("rules_snapshot_json");

                    b.Property<string>("Sid")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("sid");

                    b.Property<string>("Star")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("star");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("TakeoffAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("takeoff_at");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_fo_pireps");

                    b.HasIndex("LegId")
                        .HasDatabaseName("ix_fo_pireps_leg_id");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_fo_pireps_status_submitted_at");

                    b.HasIndex("TourId", "Vid")
                        .HasDatabaseName("ix_fo_pireps_tour_id_vid");

                    b.HasIndex("Vid", "TakeoffAt")
                        .HasDatabaseName("ix_fo_pireps_vid_takeoff_at");

                    b.ToTable("fo_pireps", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.PirepEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<int>("ByVid")
                        .HasColumnType("int")
                        .HasColumnName("by_vid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("note");

                    b.Property<long>("PirepId")
                        .HasColumnType("bigint")
                        .HasColumnName("pirep_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_fo_pirep_events");

                    b.HasIndex("PirepId", "At")
                        .HasDatabaseName("ix_fo_pirep_events_pirep_id_at");

                    b.ToTable("fo_pirep_events", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.PirepFlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aircraft")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("aircraft");

                    b.Property<string>("ArrivalIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arrival_icao");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("callsign");

                    b.Property<long?>("ClaimedSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("claimed_session_id");

                    b.Property<string>("DepartureIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("departure_icao");

                    b.Property<string>("FlightPlansJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("flight_plans_json");

                    b.Property<DateTime?>("LandingAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("landing_at");

                    b.Property<long>("PirepId")
                        .HasColumnType("bigint")
                        .HasColumnName("pirep_id");

                    b.Property<int?>("PlanAtTakeoffRevision")
                        .HasColumnType("int")
                        .HasColumnName("plan_at_takeoff_revision");

                    b.Property<int>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.Property<DateTime>("TakeoffAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("takeoff_at");

                    b.Property<long>("TrackerSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("tracker_session_id");

                    b.HasKey("Id")
                        .HasName("pk_fo_pirep_flights");

                    b.HasIndex("ClaimedSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_pirep_flights_claimed_session_id");

                    b.HasIndex("PirepId")
                        .HasDatabaseName("ix_fo_pirep_flights_pirep_id");

                    b.HasIndex("TrackerSessionId")
                        .HasDatabaseName("ix_fo_pirep_flights_tracker_session_id");

                    b.ToTable("fo_pirep_flights", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("category");

                    b.Property<string>("CheckKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("check_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("examples_i18n");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("name_i18n");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retired_at");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int?>("YearlyMax")
                        .HasColumnType("int")
                        .HasColumnName("yearly_max");

                    b.HasKey("Id")
                        .HasName("pk_fo_errors");

                    b.ToTable("fo_errors", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AmendsRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("amends_rule_id");

                    b.Property<string>("CheckKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("check_key");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retired_at");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("text_i18n");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<long?>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_rules");

                    b.HasIndex("AmendsRuleId")
                        .HasDatabaseName("ix_fo_rules_amends_rule_id");

                    b.HasIndex("TourId", "Sort")
                        .HasDatabaseName("ix_fo_rules_tour_id_sort");

                    b.ToTable("fo_rules", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourRuleError", b =>
                {
                    b.Property<long>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<long>("ErrorId")
                        .HasColumnType("bigint")
                        .HasColumnName("error_id");

                    b.HasKey("RuleId", "ErrorId")
                        .HasName("pk_fo_rule_errors");

                    b.HasIndex("ErrorId")
                        .HasDatabaseName("ix_fo_rule_errors_error_id");

                    b.ToTable("fo_rule_errors", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.CallsignRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<long?>("LegId")
                        .HasColumnType("bigint")
                        .HasColumnName("leg_id");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("match");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("mode");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_fo_callsign_rules");

                    b.HasIndex("LegId")
                        .HasDatabaseName("ix_fo_callsign_rules_leg_id");

                    b.HasIndex("TourId", "LegId")
                        .HasDatabaseName("ix_fo_callsign_rules_tour_id_leg_id");

                    b.ToTable("fo_callsign_rules", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.Rotation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<long>("HubId")
                        .HasColumnType("bigint")
                        .HasColumnName("hub_id");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_rotations");

                    b.HasIndex("HubId")
                        .HasDatabaseName("ix_fo_rotations_hub_id");

                    b.HasIndex("TourId", "HubId", "Sort")
                        .HasDatabaseName("ix_fo_rotations_tour_id_hub_id_sort");

                    b.ToTable("fo_rotations", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.TourConstraint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_tour_constraints");

                    b.HasIndex("TourId", "Kind")
                        .HasDatabaseName("ix_fo_tour_constraints_tour_id_kind");

                    b.ToTable("fo_tour_constraints", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.TourHub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fo_hubs");

                    b.HasIndex("TourId", "Icao")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_hubs_tour_id_icao");

                    b.ToTable("fo_hubs", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Tours.Tour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedAircraftJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("allowed_aircraft_json");

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<long?>("BannerMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("banner_media_id");

                    b.Property<string>("BriefingJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("briefing_json");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("close_at");

                    b.Property<bool>("CloseFromParent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("close_from_parent");

                    b.Property<long?>("CoverMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_media_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("DailyLegLimit")
                        .HasColumnType("int")
                        .HasColumnName("daily_leg_limit");

                    b.Property<string>("HubRotationOrder")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("hub_rotation_order");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_template");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<int?>("MinPilotRating")
                        .HasColumnType("int")
                        .HasColumnName("min_pilot_rating");

                    b.Property<string>("OpenGoal")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("open_goal");

                    b.Property<string>("OpenGoalJson")
                        .HasColumnType("json")
                        .HasColumnName("open_goal_json");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<long?>("ParentTourId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_tour_id");

                    b.Property<string>("Progression")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("progression");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("ReferenceAircraftIcao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("reference_aircraft_icao");

                    b.Property<DateTime?>("ReleaseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_at");

                    b.Property<bool>("ReleaseFromParent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("release_from_parent");

                    b.Property<int>("ReportWindowDays")
                        .HasColumnType("int")
                        .HasColumnName("report_window_days");

                    b.Property<int?>("RequiredNm")
                        .HasColumnType("int")
                        .HasColumnName("required_nm");

                    b.Property<int?>("RequiredSubtours")
                        .HasColumnType("int")
                        .HasColumnName("required_subtours");

                    b.Property<bool>("RequiresProcedures")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_procedures");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("ShowPreview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_preview");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("summary_i18n");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_fo_tours");

                    b.HasIndex("ParentTourId")
                        .HasDatabaseName("ix_fo_tours_parent_tour_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_fo_tours_slug");

                    b.HasIndex("IsTemplate", "ReleaseAt")
                        .HasDatabaseName("ix_fo_tours_is_template_release_at");

                    b.ToTable("fo_tours", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Legs.Leg", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Shape.Rotation", null)
                        .WithMany()
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_fo_legs_rotations_rotation_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_legs_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Enrolment", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fo_enrolments_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Pirep", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Legs.Leg", null)
                        .WithMany()
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fo_pireps_fo_legs_leg_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fo_pireps_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.PirepEvent", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Pireps.Pirep", null)
                        .WithMany("Events")
                        .HasForeignKey("PirepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_pirep_events_fo_pireps_pirep_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.PirepFlight", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Pireps.Pirep", null)
                        .WithMany("Flights")
                        .HasForeignKey("PirepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_pirep_flights_fo_pireps_pirep_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourRule", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Rules.TourRule", null)
                        .WithMany()
                        .HasForeignKey("AmendsRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fo_rules_fo_rules_amends_rule_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_fo_rules_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourRuleError", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Rules.TourError", null)
                        .WithMany()
                        .HasForeignKey("ErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_rule_errors_fo_errors_error_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Rules.TourRule", null)
                        .WithMany("ErrorLinks")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_rule_errors_fo_rules_rule_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.CallsignRule", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Legs.Leg", null)
                        .WithMany()
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_fo_callsign_rules_fo_legs_leg_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_callsign_rules_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.Rotation", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Shape.TourHub", null)
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_rotations_fo_hubs_hub_id");

                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_rotations_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.TourConstraint", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_tour_constraints_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Shape.TourHub", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fo_hubs_fo_tours_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Tours.Tour", b =>
                {
                    b.HasOne("IvaoHub.Modules.FlightOps.Tours.Tour", null)
                        .WithMany()
                        .HasForeignKey("ParentTourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fo_tours_fo_tours_parent_tour_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Pireps.Pirep", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("IvaoHub.Modules.FlightOps.Rules.TourRule", b =>
                {
                    b.Navigation("ErrorLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
