// <auto-generated />
using System;
using IvaoHub.Modules.Events.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaoHub.Modules.Events.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20261006161603_AddEventSlots")]
    partial class AddEventSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IvaoHub.Core.Content.AwardSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AwardId")
                        .HasColumnType("bigint")
                        .HasColumnName("award_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notified_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_cms_award_signals");

                    b.HasIndex("Status", "NotifiedAt")
                        .HasDatabaseName("ix_cms_award_signals_status_notified_at");

                    b.HasIndex("Vid", "Status")
                        .HasDatabaseName("ix_cms_award_signals_vid_status");

                    b.HasIndex("SourceModule", "SourceId", "Vid")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_award_signals_source_module_source_id_vid");

                    b.ToTable("cms_award_signals", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.CalendarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("json")
                        .HasColumnName("description_i18n");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_calendar_entries");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_starts_at_utc");

                    b.HasIndex("OwnerDepartment", "StartsAtUtc")
                        .HasDatabaseName("ix_cms_calendar_entries_owner_department_starts_at_utc");

                    b.HasIndex("SourceModule", "SourceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_calendar_entries_source_module_source_id_sequence");

                    b.ToTable("cms_calendar_entries", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("general")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("participants_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cms_contact_messages");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("ix_cms_contact_messages_created_by_created_at");

                    b.HasIndex("OwnerDepartment", "Status", "CreatedAt")
                        .HasDatabaseName("ix_cms_contact_messages_owner_department_status_created_at");

                    b.HasIndex("SourceModule", "SourceId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_contact_messages_source_module_source_id_kind");

                    b.ToTable("cms_contact_messages", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("label_i18n");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.HasKey("Id")
                        .HasName("pk_cms_contact_references");

                    b.HasIndex("SourceModule", "SourceId")
                        .HasDatabaseName("ix_cms_contact_references_source_module_source_id");

                    b.HasIndex("MessageId", "SourceModule", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_contact_references_message_id_source_module_source_id");

                    b.ToTable("cms_contact_references", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.MediaUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<DateTime?>("UsedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_until");

                    b.HasKey("Id")
                        .HasName("pk_cms_media_uses");

                    b.HasIndex("MediaId", "UsedUntil")
                        .HasDatabaseName("ix_cms_media_uses_media_id_used_until");

                    b.HasIndex("SourceModule", "SourceId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_media_uses_source_module_source_id_media_id");

                    b.ToTable("cms_media_uses", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Content.SearchIndexEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("locale");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_module");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("url");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_cms_search_index");

                    b.HasIndex("Locale", "UpdatedAt")
                        .HasDatabaseName("ix_cms_search_index_locale_updated_at");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("ix_cms_search_index_fulltext")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex("SourceModule", "SourceId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_cms_search_index_source_module_source_id_locale");

                    b.ToTable("cms_search_index", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Core.Services.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("json")
                        .HasColumnName("after_json");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("json")
                        .HasColumnName("before_json");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_superadmin");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<int>("Vid")
                        .HasColumnType("int")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("pk_hub_audit_log");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_hub_audit_log_entity_entity_id");

                    b.HasIndex("Vid", "At")
                        .HasDatabaseName("ix_hub_audit_log_vid_at");

                    b.ToTable("hub_audit_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AfterDoneAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("after_done_at");

                    b.Property<long?>("BannerMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("banner_media_id");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("body_json");

                    b.Property<DateTime?>("BookingOpensAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("booking_opens_at_utc");

                    b.Property<string>("CancellationNote")
                        .HasColumnType("json")
                        .HasColumnName("cancellation_note_i18n");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("external_url");

                    b.Property<bool>("HasRoster")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_roster");

                    b.Property<bool>("InPerson")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("in_person");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("organizer");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<bool>("PrivateSlots")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("private_slots");

                    b.Property<bool>("PublicSlots")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("public_slots");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<int?>("RestrictedMaxPerEvent")
                        .HasColumnType("int")
                        .HasColumnName("restricted_max_per_event");

                    b.Property<int?>("RestrictedMaxPerWindow")
                        .HasColumnType("int")
                        .HasColumnName("restricted_max_per_window");

                    b.Property<int?>("RestrictedWindowHours")
                        .HasColumnType("int")
                        .HasColumnName("restricted_window_hours");

                    b.Property<DateTime?>("RosterProposedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("roster_proposed_at");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("ShiftMinutes")
                        .HasColumnType("int")
                        .HasColumnName("shift_minutes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("summary_i18n");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("title_i18n");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Venue")
                        .HasColumnType("json")
                        .HasColumnName("venue_i18n");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("visibility");

                    b.Property<DateTime?>("VisibleFromUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("visible_from_utc");

                    b.Property<bool>("WholeDivision")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("whole_division");

                    b.HasKey("Id")
                        .HasName("pk_evt_events");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_evt_events_slug");

                    b.HasIndex("Status", "StartsAtUtc")
                        .HasDatabaseName("ix_evt_events_status_starts_at_utc");

                    b.ToTable("evt_events", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventAirport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao");

                    b.Property<int?>("MaxArrivalsPerHour")
                        .HasColumnType("int")
                        .HasColumnName("max_arrivals_per_hour");

                    b.Property<int?>("MaxDeparturesPerHour")
                        .HasColumnType("int")
                        .HasColumnName("max_departures_per_hour");

                    b.Property<int?>("MaxMovementsPerHour")
                        .HasColumnType("int")
                        .HasColumnName("max_movements_per_hour");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_evt_event_airports");

                    b.HasIndex("EventId", "Icao")
                        .IsUnique()
                        .HasDatabaseName("ix_evt_event_airports_event_id_icao");

                    b.ToTable("evt_event_airports", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArrivalIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arrival_icao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartureIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("departure_icao");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("Remarks")
                        .HasColumnType("json")
                        .HasColumnName("remarks_i18n");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("route");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_evt_routes");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_evt_routes_event_id");

                    b.ToTable("evt_routes", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AircraftTypesJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("aircraft_types");

                    b.Property<string>("ArrivalIcao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("arrival_icao");

                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("callsign");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartureIcao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("departure_icao");

                    b.Property<string>("EventAirportIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("event_airport_icao");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("flight_number");

                    b.Property<bool>("Generated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("generated");

                    b.Property<bool>("IsArrival")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_arrival");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("OffBlockUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("off_block_utc");

                    b.Property<DateTime?>("OnBlockUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("on_block_utc");

                    b.Property<string>("OwnerDepartment")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("owner_department");

                    b.Property<int>("OwnerDepartmentMask")
                        .HasColumnType("int")
                        .HasColumnName("owner_department_mask");

                    b.Property<string>("RotationCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("rotation_code");

                    b.Property<int?>("RotationLeg")
                        .HasColumnType("int")
                        .HasColumnName("rotation_leg");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Stand")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("stand");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_evt_slots");

                    b.HasIndex("EventId", "Callsign", "OffBlockUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_evt_slots_event_id_callsign_off_block_utc");

                    b.ToTable("evt_slots", (string)null);
                });

            modelBuilder.Entity("IvaoHub.Core.Content.ContactReference", b =>
                {
                    b.HasOne("IvaoHub.Core.Content.ContactMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cms_contact_references_cms_contact_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventAirport", b =>
                {
                    b.HasOne("IvaoHub.Modules.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evt_event_airports_evt_events_event_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventRoute", b =>
                {
                    b.HasOne("IvaoHub.Modules.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evt_routes_evt_events_event_id");
                });

            modelBuilder.Entity("IvaoHub.Modules.Events.EventSlot", b =>
                {
                    b.HasOne("IvaoHub.Modules.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evt_slots_evt_events_event_id");
                });
#pragma warning restore 612, 618
        }
    }
}
