/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BootstrapResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeSetLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/data/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BlockData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LinksList"];
        put?: never;
        post: operations["LinksCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LinksGet"];
        put: operations["LinksUpdate"];
        post?: never;
        delete: operations["LinksDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentList"];
        put?: never;
        post: operations["ContentCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentGet"];
        put: operations["ContentUpdate"];
        post?: never;
        delete: operations["ContentDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/from-template/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentCreateFromTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentPublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/public/{kind}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentPublicRead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrantsList"];
        put?: never;
        post: operations["GrantsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrantsGet"];
        put: operations["GrantsUpdate"];
        post?: never;
        delete: operations["GrantsDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/superadmins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuperadminsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/superadmins/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SuperadminsAdd"];
        delete: operations["SuperadminsRemove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modules/{key}/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ModuleSetMaintenance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AtcPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What `GET /api/atc/ping` answers. Typed, so that it reaches the OpenAPI document
         *                 and from there the generated client, like every other response of the hub.
         */
        AtcPing: {
            module: string;
        };
        /**
         * @description One row in full. `BeforeJson` and `AfterJson` are the scalar columns as they were and
         *     as they became, exactly as the interceptor wrote them: they travel as text, because what they
         *     contain depends on the entity and the hub does not model it.
         */
        AuditDetailDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            vid: number;
            action: string;
            entity: string;
            entityId: string;
            beforeJson: null | string;
            afterJson: null | string;
            isSuperadmin: boolean;
            ip: null | string;
            /** Format: date-time */
            at: string;
        };
        /** @description One row of the audit log, as the list shows it. The before and after stay out. */
        AuditListDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            vid: number;
            action: string;
            entity: string;
            entityId: string;
            isSuperadmin: boolean;
            ip: null | string;
            /** Format: date-time */
            at: string;
        };
        /**
         * @description What a block is made of. A BlockKind.Content block draws what an editor typed into it; a
         *     BlockKind.Data block draws what the hub knows, asked of a provider (design M0 section 5.4).
         * @enum {unknown}
         */
        BlockKind: "Content" | "Data";
        /**
         * @description One block, as the server declares it. What it looks like and what its properties mean live in
         *     TypeScript and nowhere else (CLAUDE.md section 2); this is the envelope side of it.
         */
        BootstrapBlock: {
            type: string;
            /** Format: int32 */
            version: number;
            kind: components["schemas"]["BlockKind"];
            alwaysLive: boolean;
        };
        BootstrapDivision: {
            code: string;
            name: {
                [key: string]: string;
            };
            locales: string[];
            defaultLocale: string;
            timezone: string;
            firStaffScope: string;
        };
        /**
         * @description One module of this build. Enabled is false for an optional module the
         *     division switched off: it is compiled in and silent, and saying so is what lets the
         *     administration screen show it as something that can be switched back on.
         */
        BootstrapModule: {
            key: string;
            department: null | string;
            enabled: boolean;
            maintenance: boolean;
        };
        BootstrapNavigation: {
            public: components["schemas"]["NavItem"][];
            staff: components["schemas"]["NavItem"][];
        };
        /** @description A department of null means the permission is held on every department. */
        BootstrapPermission: {
            name: string;
            department: null | string;
        };
        /**
         * @description One permission of the catalogue: core plus whatever the installed modules declare. It is here so
         *     that the screen which hands a permission out can offer the ones that exist rather than a text
         *     box — the set is not knowable at compile time, because it depends on which modules were built in.
         *     Not sensitive: the catalogue is in the source of every fork. What is sensitive is who
         *     holds what, and that is Permissions above, which only ever describes the caller.
         */
        BootstrapPermissionName: {
            name: string;
            isGlobal: boolean;
        };
        BootstrapRegistries: {
            blocks: components["schemas"]["BootstrapBlock"][];
            widgets: components["schemas"]["BootstrapWidget"][];
            permissions: components["schemas"]["BootstrapPermissionName"][];
        };
        /**
         * @description The bootstrap payload. Menu entries are translation keys, never text: the server does not know
         *     which language the browser is showing.
         */
        BootstrapResponse: {
            user: null | components["schemas"]["BootstrapUser"];
            permissions: components["schemas"]["BootstrapPermission"][];
            division: components["schemas"]["BootstrapDivision"];
            modules: components["schemas"]["BootstrapModule"][];
            navigation: components["schemas"]["BootstrapNavigation"];
            registries: components["schemas"]["BootstrapRegistries"];
            version: string;
        };
        BootstrapUser: {
            /** Format: int32 */
            vid: number;
            firstName: string;
            lastName: string;
            positions: string[];
            isStaff: boolean;
            isSuperadmin: boolean;
            hasAllDepartments: boolean;
            locale: string;
            departments: string[];
            firs: string[];
        };
        /** @description One dashboard tile, on the same terms as a block: the envelope, never the drawing. */
        BootstrapWidget: {
            key: string;
            department: null | string;
            titleKey: string;
            sizes: string[];
        };
        /**
         * @description A content row in full, as the editor loads it. JsonNode ContentDetailDto.Body travels as the JSON it is:
         *     the backend never learned what a block means and it is not going to start here.
         */
        ContentDetailDto: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["ContentKind"];
            slug: string;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            status: components["schemas"]["PublishStatus"];
            /** Format: int64 */
            templateId: null | number;
            isTemplate: boolean;
            title: components["schemas"]["LocalizedOfstring"];
            summary: null | components["schemas"]["LocalizedOfstring"];
            seo: null | components["schemas"]["LocalizedOfJsonNode"];
            body: components["schemas"]["JsonNode"];
            /** Format: int32 */
            schemaVersion: number;
            /** Format: int64 */
            publishedVersionId: null | number;
            /** Format: date-time */
            publishedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            createdBy: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            updatedBy: number;
            /** Format: date-time */
            rowVersion: string;
        };
        /** @description What "new from template" needs to know that the template does not say. */
        ContentFromTemplateRequest: {
            ownerDepartment: components["schemas"]["Department"];
            slug: string;
        };
        /**
         * @description What an editorial row is. One table for all three (plan section 9.3).
         * @enum {unknown}
         */
        ContentKind: "Page" | "News" | "Document";
        /**
         * @description A content row as a list shows it. The body is deliberately absent: a list of pages does not
         *     need a megabyte of blocks per row to draw a table.
         */
        ContentListDto: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["ContentKind"];
            slug: string;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            status: components["schemas"]["PublishStatus"];
            isTemplate: boolean;
            title: components["schemas"]["LocalizedOfstring"];
            /** Format: date-time */
            publishedAt: null | string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description What publication is told, beyond which row it is about. */
        ContentPublishRequest: {
            /** @description A line for the staff about what changed. Never shown to a visitor. */
            changelog: null | string;
        };
        /**
         * @description What a client may set on a content row.
         *     Four things are missing on purpose. The audit columns and publishedAt are filled by
         *     the interceptor and by publication. status is not a field either: a page becomes public
         *     by being published, which is an endpoint with its own permission, not a checkbox. And
         *     templateId is written once, by "new from template", so that the record of where a page
         *     came from cannot be rewritten afterwards.
         */
        ContentWriteDto: {
            kind: components["schemas"]["ContentKind"];
            slug: string;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            isTemplate: boolean;
            title: components["schemas"]["LocalizedOfstring"];
            summary: null | components["schemas"]["LocalizedOfstring"];
            seo: null | components["schemas"]["LocalizedOfJsonNode"];
            body: components["schemas"]["JsonNode"];
            /** Format: int32 */
            schemaVersion: number;
            /** Format: date-time */
            rowVersion: string;
        };
        /**
         * @description Owner of a row. These are the department codes IVAO itself uses, so a staff position maps onto a
         *     department without a translation table (plan section 7). Stored as a string, never as a number.
         *     Note that the codes are not a mechanical suffix: ATC operations is AOD but training
         *     is TD, and headquarters is plain HQ.
         * @enum {unknown}
         */
        Department: "HQ" | "SOD" | "FOD" | "AOD" | "TD" | "MD" | "ED" | "PRD" | "WD";
        /** @description A grant as the form loads it, with the audit trail and the version to write back. */
        GrantDetailDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            vid: number;
            kind: components["schemas"]["GrantKind"];
            value: string;
            department: null | components["schemas"]["Department"];
            effect: components["schemas"]["GrantEffect"];
            /** Format: date-time */
            expiresAt: null | string;
            /** Format: date-time */
            suspendedAt: null | string;
            reason: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            createdBy: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            updatedBy: number;
            /** Format: date-time */
            rowVersion: string;
        };
        /**
         * @description What a grant does to a permission.
         * @enum {unknown}
         */
        GrantEffect: "Grant" | "Deny";
        /**
         * @description What a grant talks about. Only permissions for now.
         * @enum {unknown}
         */
        GrantKind: "Permission";
        /**
         * @description A grant as the list shows it. There is no department to narrow this list by: a grant is a
         *     global resource, read and written behind `Permissions.Manage` and nothing else
         *     (design M0 section 3.9).
         */
        GrantListDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            vid: number;
            value: string;
            department: null | components["schemas"]["Department"];
            effect: components["schemas"]["GrantEffect"];
            /** Format: date-time */
            expiresAt: null | string;
            /** Format: date-time */
            suspendedAt: null | string;
            reason: null | string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description What an administrator may set.
         *     SuspendedAt is deliberately absent: it is written by the login when IVAO stops
         *     listing the member as staff, and a grant is suspended rather than deleted so that it comes back
         *     on its own if the position does. Letting a form set it would make the two meanings of "this
         *     grant is asleep" indistinguishable.
         */
        GrantWriteDto: {
            /** Format: int32 */
            vid: number;
            kind: components["schemas"]["GrantKind"];
            value: string;
            department: null | components["schemas"]["Department"];
            effect: components["schemas"]["GrantEffect"];
            /** Format: date-time */
            expiresAt: null | string;
            reason: null | string;
            /** Format: date-time */
            rowVersion: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        JsonNode: unknown;
        /** @description A link as the form shows it, with the audit trail and the version to write back. */
        LinkDetailDto: {
            /** Format: int64 */
            id: number;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            description: null | components["schemas"]["LocalizedOfstring"];
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            createdBy: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            updatedBy: number;
            /** Format: date-time */
            rowVersion: string;
        };
        /**
         * @description A link as a list shows it. Translated fields travel whole — the browser knows which language it
         *     is drawing, the server does not — so there is no "give me the Italian list" endpoint.
         */
        LinkListDto: {
            /** Format: int64 */
            id: number;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description What a client may set. The audit columns are absent on purpose: the interceptor fills them, and
         *     a payload that could carry them would be a payload that could lie about them.
         *     DateTime LinkWriteDto.RowVersion is the version the form was loaded with. Sending back a stale one
         *     is how the server finds out that somebody else saved first, and answers 409.
         */
        LinkWriteDto: {
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            description: null | components["schemas"]["LocalizedOfstring"];
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            rowVersion: string;
        };
        /** @description The language as the division spells it, which is what the client should settle on. */
        LocaleResponse: {
            locale: string;
        };
        /** @description The language a member is choosing, as they spell it: `it`, or `it-IT`. */
        LocaleWriteDto: {
            locale: string;
        };
        /**
         * @description A field translated into the languages of the division: one JSON column on the row, never a
         *     separate translations table (plan section 16.1). Keys are language codes ("it", "en") and are
         *     kept sorted so that two equal values always serialise to the same JSON.
         */
        LocalizedOfJsonNode: {
            [key: string]: unknown;
        };
        /**
         * @description A field translated into the languages of the division: one JSON column on the row, never a
         *     separate translations table (plan section 16.1). Keys are language codes ("it", "en") and are
         *     kept sorted so that two equal values always serialise to the same JSON.
         */
        LocalizedOfstring: {
            [key: string]: string;
        };
        /** @description What an administrator sets on a module. One switch, and that is the whole screen. */
        ModuleMaintenanceRequest: {
            maintenance: boolean;
        };
        /** @description Key is a translation key such as `nav.home`. */
        NavItem: {
            key: string;
            path: string;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfAuditListDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["AuditListDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfContentListDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["ContentListDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfGrantListDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["GrantListDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfLinkListDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["LinkListDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfSearchHitDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["SearchHitDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /**
         * @description What the public site is given: the published version and nothing about the draft behind it.
         *     There is no row version, no audit trail and no status, because a visitor has nothing to do with
         *     any of them.
         */
        PublicContentDto: {
            kind: components["schemas"]["ContentKind"];
            slug: string;
            title: components["schemas"]["LocalizedOfstring"];
            summary: null | components["schemas"]["LocalizedOfstring"];
            seo: null | components["schemas"]["LocalizedOfJsonNode"];
            body: components["schemas"]["JsonNode"];
            /** Format: int32 */
            schemaVersion: number;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            publishedAt: string;
        };
        /**
         * @description Editorial state. The public site only ever reads published rows.
         * @enum {unknown}
         */
        PublishStatus: "Draft" | "Published";
        /** @description One hit. What it is and where it lives; the page itself is fetched by following it. */
        SearchHitDto: {
            sourceModule: string;
            sourceId: string;
            kind: string;
            url: string;
            ownerDepartment: components["schemas"]["Department"];
            title: string;
        };
        /** @description What was deployed. Anonymous, and never cached, so a report can quote a build. */
        VersionResponse: {
            version: string;
            commit: string;
            /** Format: date-time */
            builtAt: string;
            dotnet: string;
        };
        /**
         * @description Who may read a row. The global query filter of F4 turns this into a where clause.
         * @enum {unknown}
         */
        Visibility: "Public" | "Members" | "Staff" | "Department";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeSetLocale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocaleWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocaleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    BlockData: {
        parameters: {
            query?: {
                props?: string;
            };
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonNode"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Search: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfSearchHitDto"];
                };
            };
        };
    };
    LinksList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                dir?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfLinkListDto"];
                };
            };
        };
    };
    LinksCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LinkWriteDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    LinksGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LinksUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LinkWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LinksDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                dir?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfContentListDto"];
                };
            };
        };
    };
    ContentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ContentWriteDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ContentGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ContentWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentCreateFromTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentFromTemplateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentPublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ContentPublishRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentPublicRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ContentKind"];
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContentDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantsList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                dir?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfGrantListDto"];
                };
            };
        };
    };
    GrantsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GrantWriteDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GrantsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GrantWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrantsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuperadminsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    SuperadminsAdd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SuperadminsRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    AuditList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                dir?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfAuditListDto"];
                };
            };
        };
    };
    AuditGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModuleSetMaintenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleMaintenanceRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AtcPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcPing"];
                };
            };
        };
    };
}
