/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BootstrapResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeSetLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LinksList"];
        put?: never;
        post: operations["LinksCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LinksGet"];
        put: operations["LinksUpdate"];
        post?: never;
        delete: operations["LinksDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BootstrapDivision: {
            code: string;
            name: {
                [key: string]: string;
            };
            locales: string[];
            defaultLocale: string;
            timezone: string;
            firStaffScope: string;
        };
        BootstrapModule: {
            key: string;
            department: null | string;
            enabled: boolean;
            maintenance: boolean;
        };
        BootstrapNavigation: {
            public: components["schemas"]["NavItem"][];
            staff: components["schemas"]["NavItem"][];
        };
        /** @description A department of null means the permission is held on every department. */
        BootstrapPermission: {
            name: string;
            department: null | string;
        };
        BootstrapRegistries: {
            blocks: string[];
            widgets: string[];
        };
        /**
         * @description The bootstrap payload. Menu entries are translation keys, never text: the server does not know
         *     which language the browser is showing.
         */
        BootstrapResponse: {
            user: null | components["schemas"]["BootstrapUser"];
            permissions: components["schemas"]["BootstrapPermission"][];
            division: components["schemas"]["BootstrapDivision"];
            modules: components["schemas"]["BootstrapModule"][];
            navigation: components["schemas"]["BootstrapNavigation"];
            registries: components["schemas"]["BootstrapRegistries"];
            version: string;
        };
        BootstrapUser: {
            /** Format: int32 */
            vid: number;
            firstName: string;
            lastName: string;
            positions: string[];
            isStaff: boolean;
            isSuperadmin: boolean;
            hasAllDepartments: boolean;
            locale: string;
            departments: string[];
            firs: string[];
        };
        /**
         * @description Owner of a row. These are the department codes IVAO itself uses, so a staff position maps onto a
         *     department without a translation table (plan section 7). Stored as a string, never as a number.
         *     Note that the codes are not a mechanical suffix: ATC operations is AOD but training
         *     is TD, and headquarters is plain HQ.
         * @enum {unknown}
         */
        Department: "HQ" | "SOD" | "FOD" | "AOD" | "TD" | "MD" | "ED" | "PRD" | "WD";
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description A link as the form shows it, with the audit trail and the version to write back. */
        LinkDetailDto: {
            /** Format: int64 */
            id: number;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            description: null | components["schemas"]["LocalizedOfstring"];
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            createdBy: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int32 */
            updatedBy: number;
            /** Format: date-time */
            rowVersion: string;
        };
        /**
         * @description A link as a list shows it. Translated fields travel whole — the browser knows which language it
         *     is drawing, the server does not — so there is no "give me the Italian list" endpoint.
         */
        LinkListDto: {
            /** Format: int64 */
            id: number;
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description What a client may set. The audit columns are absent on purpose: the interceptor fills them, and
         *     a payload that could carry them would be a payload that could lie about them.
         *     DateTime LinkWriteDto.RowVersion is the version the form was loaded with. Sending back a stale one
         *     is how the server finds out that somebody else saved first, and answers 409.
         */
        LinkWriteDto: {
            ownerDepartment: components["schemas"]["Department"];
            visibility: components["schemas"]["Visibility"];
            title: components["schemas"]["LocalizedOfstring"];
            url: string;
            description: null | components["schemas"]["LocalizedOfstring"];
            category: null | string;
            /** Format: int32 */
            sort: number;
            isActive: boolean;
            /** Format: date-time */
            rowVersion: string;
        };
        /** @description The language as the division spells it, which is what the client should settle on. */
        LocaleResponse: {
            locale: string;
        };
        /** @description The language a member is choosing, as they spell it: `it`, or `it-IT`. */
        LocaleWriteDto: {
            locale: string;
        };
        /**
         * @description A field translated into the languages of the division: one JSON column on the row, never a
         *     separate translations table (plan section 16.1). Keys are language codes ("it", "en") and are
         *     kept sorted so that two equal values always serialise to the same JSON.
         */
        LocalizedOfstring: {
            [key: string]: string;
        };
        /** @description Key is a translation key such as `nav.home`. */
        NavItem: {
            key: string;
            path: string;
        };
        /**
         * @description One page of a list, in the shape every list of the hub answers with. Paging is decided in the
         *     CRUD engine and nowhere else, so a screen never invents its own envelope (design M0 section 3.9).
         */
        PagedResultOfLinkListDto: {
            /** @description The rows of this page, already mapped to their list shape. */
            items: components["schemas"]["LinkListDto"][];
            /**
             * Format: int32
             * @description One based page number.
             */
            page: number;
            /**
             * Format: int32
             * @description How many rows a page holds.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many rows the whole filtered set holds.
             */
            total: number;
        };
        /** @description What was deployed. Anonymous, and never cached, so a report can quote a build. */
        VersionResponse: {
            version: string;
            commit: string;
            /** Format: date-time */
            builtAt: string;
            dotnet: string;
        };
        /**
         * @description Who may read a row. The global query filter of F4 turns this into a where clause.
         * @enum {unknown}
         */
        Visibility: "Public" | "Members" | "Staff" | "Department";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeSetLocale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocaleWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocaleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    LinksList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                dir?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfLinkListDto"];
                };
            };
        };
    };
    LinksCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LinkWriteDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    LinksGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LinksUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LinkWriteDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LinksDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
