/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as MemberContactRouteImport } from './routes/_member/contact'
import { Route as MemberMeRouteImport } from './routes/_member/me'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSlugRouteImport } from './routes/_public/$slug'
import { Route as PublicCalendarRouteImport } from './routes/_public/calendar'
import { Route as PublicForbiddenRouteImport } from './routes/_public/forbidden'
import { Route as PublicLoginErrorRouteImport } from './routes/_public/login-error'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicDocumentsIndexRouteImport } from './routes/_public/documents.index'
import { Route as PublicDocumentsSlugRouteImport } from './routes/_public/documents.$slug'
import { Route as PublicNewsIndexRouteImport } from './routes/_public/news.index'
import { Route as PublicNewsSlugRouteImport } from './routes/_public/news.$slug'
import { Route as StaffStaffIndexRouteImport } from './routes/_staff/staff.index'
import { Route as StaffStaffContentRouteImport } from './routes/_staff/staff.content'
import { Route as StaffStaffLinksRouteImport } from './routes/_staff/staff.links'
import { Route as StaffStaffMediaRouteImport } from './routes/_staff/staff.media'
import { Route as StaffStaffDeptIndexRouteImport } from './routes/_staff/staff.$dept.index'
import { Route as StaffStaffDeptCalendarRouteImport } from './routes/_staff/staff.$dept.calendar'
import { Route as StaffStaffDeptCategoriesRouteImport } from './routes/_staff/staff.$dept.categories'
import { Route as StaffStaffDeptContactsRouteImport } from './routes/_staff/staff.$dept.contacts'
import { Route as StaffStaffDeptMenuRouteImport } from './routes/_staff/staff.$dept.menu'
import { Route as StaffStaffAdminAuditRouteImport } from './routes/_staff/staff.admin.audit'
import { Route as StaffStaffAdminModulesRouteImport } from './routes/_staff/staff.admin.modules'
import { Route as StaffStaffAdminPermissionsRouteImport } from './routes/_staff/staff.admin.permissions'
import { Route as StaffStaffAdminUiKitRouteImport } from './routes/_staff/staff.admin.ui-kit'
import { Route as StaffStaffContentIndexRouteImport } from './routes/_staff/staff.content.index'
import { Route as StaffStaffContentIdRouteImport } from './routes/_staff/staff.content.$id'
import { Route as StaffStaffLinksIndexRouteImport } from './routes/_staff/staff.links.index'
import { Route as StaffStaffLinksIdRouteImport } from './routes/_staff/staff.links.$id'
import { Route as StaffStaffMediaIndexRouteImport } from './routes/_staff/staff.media.index'
import { Route as StaffStaffMediaIdRouteImport } from './routes/_staff/staff.media.$id'
import { Route as StaffStaffDeptCalendarIndexRouteImport } from './routes/_staff/staff.$dept.calendar.index'
import { Route as StaffStaffDeptCalendarIdRouteImport } from './routes/_staff/staff.$dept.calendar.$id'
import { Route as StaffStaffDeptCategoriesIndexRouteImport } from './routes/_staff/staff.$dept.categories.index'
import { Route as StaffStaffDeptCategoriesIdRouteImport } from './routes/_staff/staff.$dept.categories.$id'
import { Route as StaffStaffDeptContactsIndexRouteImport } from './routes/_staff/staff.$dept.contacts.index'
import { Route as StaffStaffDeptContactsIdRouteImport } from './routes/_staff/staff.$dept.contacts.$id'
import { Route as StaffStaffDeptDashboardIdRouteImport } from './routes/_staff/staff.$dept.dashboard.$id'
import { Route as StaffStaffDeptMenuIndexRouteImport } from './routes/_staff/staff.$dept.menu.index'
import { Route as StaffStaffDeptMenuIdRouteImport } from './routes/_staff/staff.$dept.menu.$id'
import { Route as StaffStaffAdminCalendarKindsIndexRouteImport } from './routes/_staff/staff.admin.calendar-kinds.index'
import { Route as StaffStaffAdminCalendarKindsIdRouteImport } from './routes/_staff/staff.admin.calendar-kinds.$id'
import { Route as StaffStaffAdminPermissionsIndexRouteImport } from './routes/_staff/staff.admin.permissions.index'
import { Route as StaffStaffAdminPermissionsIdRouteImport } from './routes/_staff/staff.admin.permissions.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberContactRoute = MemberContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMeRoute = MemberMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MemberRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCalendarRoute = PublicCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForbiddenRoute = PublicForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginErrorRoute = PublicLoginErrorRouteImport.update({
  id: '/login-error',
  path: '/login-error',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsIndexRoute = PublicDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsSlugRoute = PublicDocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const StaffStaffIndexRoute = StaffStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffContentRoute = StaffStaffContentRouteImport.update({
  id: '/staff/content',
  path: '/staff/content',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffLinksRoute = StaffStaffLinksRouteImport.update({
  id: '/staff/links',
  path: '/staff/links',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffMediaRoute = StaffStaffMediaRouteImport.update({
  id: '/staff/media',
  path: '/staff/media',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptIndexRoute = StaffStaffDeptIndexRouteImport.update({
  id: '/staff/$dept/',
  path: '/staff/$dept/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptCalendarRoute = StaffStaffDeptCalendarRouteImport.update({
  id: '/staff/$dept/calendar',
  path: '/staff/$dept/calendar',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptCategoriesRoute =
  StaffStaffDeptCategoriesRouteImport.update({
    id: '/staff/$dept/categories',
    path: '/staff/$dept/categories',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffDeptContactsRoute = StaffStaffDeptContactsRouteImport.update({
  id: '/staff/$dept/contacts',
  path: '/staff/$dept/contacts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptMenuRoute = StaffStaffDeptMenuRouteImport.update({
  id: '/staff/$dept/menu',
  path: '/staff/$dept/menu',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminAuditRoute = StaffStaffAdminAuditRouteImport.update({
  id: '/staff/admin/audit',
  path: '/staff/admin/audit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminModulesRoute = StaffStaffAdminModulesRouteImport.update({
  id: '/staff/admin/modules',
  path: '/staff/admin/modules',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminPermissionsRoute =
  StaffStaffAdminPermissionsRouteImport.update({
    id: '/staff/admin/permissions',
    path: '/staff/admin/permissions',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffAdminUiKitRoute = StaffStaffAdminUiKitRouteImport.update({
  id: '/staff/admin/ui-kit',
  path: '/staff/admin/ui-kit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffContentIndexRoute = StaffStaffContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffStaffContentRoute,
} as any)
const StaffStaffContentIdRoute = StaffStaffContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffContentRoute,
} as any)
const StaffStaffLinksIndexRoute = StaffStaffLinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffStaffLinksRoute,
} as any)
const StaffStaffLinksIdRoute = StaffStaffLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffLinksRoute,
} as any)
const StaffStaffMediaIndexRoute = StaffStaffMediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffStaffMediaRoute,
} as any)
const StaffStaffMediaIdRoute = StaffStaffMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffMediaRoute,
} as any)
const StaffStaffDeptCalendarIndexRoute =
  StaffStaffDeptCalendarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptCalendarRoute,
  } as any)
const StaffStaffDeptCalendarIdRoute =
  StaffStaffDeptCalendarIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffDeptCalendarRoute,
  } as any)
const StaffStaffDeptCategoriesIndexRoute =
  StaffStaffDeptCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptCategoriesRoute,
  } as any)
const StaffStaffDeptCategoriesIdRoute =
  StaffStaffDeptCategoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffDeptCategoriesRoute,
  } as any)
const StaffStaffDeptContactsIndexRoute =
  StaffStaffDeptContactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptContactsRoute,
  } as any)
const StaffStaffDeptContactsIdRoute =
  StaffStaffDeptContactsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffDeptContactsRoute,
  } as any)
const StaffStaffDeptDashboardIdRoute =
  StaffStaffDeptDashboardIdRouteImport.update({
    id: '/staff/$dept/dashboard/$id',
    path: '/staff/$dept/dashboard/$id',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffDeptMenuIndexRoute = StaffStaffDeptMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffStaffDeptMenuRoute,
} as any)
const StaffStaffDeptMenuIdRoute = StaffStaffDeptMenuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptMenuRoute,
} as any)
const StaffStaffAdminCalendarKindsIndexRoute =
  StaffStaffAdminCalendarKindsIndexRouteImport.update({
    id: '/staff/admin/calendar-kinds/',
    path: '/staff/admin/calendar-kinds/',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffAdminCalendarKindsIdRoute =
  StaffStaffAdminCalendarKindsIdRouteImport.update({
    id: '/staff/admin/calendar-kinds/$id',
    path: '/staff/admin/calendar-kinds/$id',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffAdminPermissionsIndexRoute =
  StaffStaffAdminPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)
const StaffStaffAdminPermissionsIdRoute =
  StaffStaffAdminPermissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/contact': typeof MemberContactRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/calendar': typeof PublicCalendarRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/search': typeof PublicSearchRoute
  '/documents/$slug': typeof PublicDocumentsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/staff/content': typeof StaffStaffContentRouteWithChildren
  '/staff/links': typeof StaffStaffLinksRouteWithChildren
  '/staff/media': typeof StaffStaffMediaRouteWithChildren
  '/documents/': typeof PublicDocumentsIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/staff/': typeof StaffStaffIndexRoute
  '/staff/$dept/calendar': typeof StaffStaffDeptCalendarRouteWithChildren
  '/staff/$dept/categories': typeof StaffStaffDeptCategoriesRouteWithChildren
  '/staff/$dept/contacts': typeof StaffStaffDeptContactsRouteWithChildren
  '/staff/$dept/menu': typeof StaffStaffDeptMenuRouteWithChildren
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/content/$id': typeof StaffStaffContentIdRoute
  '/staff/links/$id': typeof StaffStaffLinksIdRoute
  '/staff/media/$id': typeof StaffStaffMediaIdRoute
  '/staff/$dept/': typeof StaffStaffDeptIndexRoute
  '/staff/content/': typeof StaffStaffContentIndexRoute
  '/staff/links/': typeof StaffStaffLinksIndexRoute
  '/staff/media/': typeof StaffStaffMediaIndexRoute
  '/staff/$dept/calendar/$id': typeof StaffStaffDeptCalendarIdRoute
  '/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/staff/$dept/contacts/$id': typeof StaffStaffDeptContactsIdRoute
  '/staff/$dept/dashboard/$id': typeof StaffStaffDeptDashboardIdRoute
  '/staff/$dept/menu/$id': typeof StaffStaffDeptMenuIdRoute
  '/staff/admin/calendar-kinds/$id': typeof StaffStaffAdminCalendarKindsIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/calendar/': typeof StaffStaffDeptCalendarIndexRoute
  '/staff/$dept/categories/': typeof StaffStaffDeptCategoriesIndexRoute
  '/staff/$dept/contacts/': typeof StaffStaffDeptContactsIndexRoute
  '/staff/$dept/menu/': typeof StaffStaffDeptMenuIndexRoute
  '/staff/admin/calendar-kinds/': typeof StaffStaffAdminCalendarKindsIndexRoute
  '/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/contact': typeof MemberContactRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/calendar': typeof PublicCalendarRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/search': typeof PublicSearchRoute
  '/documents/$slug': typeof PublicDocumentsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/documents': typeof PublicDocumentsIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/staff': typeof StaffStaffIndexRoute
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/content/$id': typeof StaffStaffContentIdRoute
  '/staff/links/$id': typeof StaffStaffLinksIdRoute
  '/staff/media/$id': typeof StaffStaffMediaIdRoute
  '/staff/$dept': typeof StaffStaffDeptIndexRoute
  '/staff/content': typeof StaffStaffContentIndexRoute
  '/staff/links': typeof StaffStaffLinksIndexRoute
  '/staff/media': typeof StaffStaffMediaIndexRoute
  '/staff/$dept/calendar/$id': typeof StaffStaffDeptCalendarIdRoute
  '/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/staff/$dept/contacts/$id': typeof StaffStaffDeptContactsIdRoute
  '/staff/$dept/dashboard/$id': typeof StaffStaffDeptDashboardIdRoute
  '/staff/$dept/menu/$id': typeof StaffStaffDeptMenuIdRoute
  '/staff/admin/calendar-kinds/$id': typeof StaffStaffAdminCalendarKindsIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/calendar': typeof StaffStaffDeptCalendarIndexRoute
  '/staff/$dept/categories': typeof StaffStaffDeptCategoriesIndexRoute
  '/staff/$dept/contacts': typeof StaffStaffDeptContactsIndexRoute
  '/staff/$dept/menu': typeof StaffStaffDeptMenuIndexRoute
  '/staff/admin/calendar-kinds': typeof StaffStaffAdminCalendarKindsIndexRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/_member/contact': typeof MemberContactRoute
  '/_member/me': typeof MemberMeRoute
  '/_public/$slug': typeof PublicSlugRoute
  '/_public/calendar': typeof PublicCalendarRoute
  '/_public/forbidden': typeof PublicForbiddenRoute
  '/_public/login-error': typeof PublicLoginErrorRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/documents/$slug': typeof PublicDocumentsSlugRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/_staff/staff/content': typeof StaffStaffContentRouteWithChildren
  '/_staff/staff/links': typeof StaffStaffLinksRouteWithChildren
  '/_staff/staff/media': typeof StaffStaffMediaRouteWithChildren
  '/_public/documents/': typeof PublicDocumentsIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_staff/staff/': typeof StaffStaffIndexRoute
  '/_staff/staff/$dept/calendar': typeof StaffStaffDeptCalendarRouteWithChildren
  '/_staff/staff/$dept/categories': typeof StaffStaffDeptCategoriesRouteWithChildren
  '/_staff/staff/$dept/contacts': typeof StaffStaffDeptContactsRouteWithChildren
  '/_staff/staff/$dept/menu': typeof StaffStaffDeptMenuRouteWithChildren
  '/_staff/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/_staff/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/_staff/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/_staff/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/_staff/staff/content/$id': typeof StaffStaffContentIdRoute
  '/_staff/staff/links/$id': typeof StaffStaffLinksIdRoute
  '/_staff/staff/media/$id': typeof StaffStaffMediaIdRoute
  '/_staff/staff/$dept/': typeof StaffStaffDeptIndexRoute
  '/_staff/staff/content/': typeof StaffStaffContentIndexRoute
  '/_staff/staff/links/': typeof StaffStaffLinksIndexRoute
  '/_staff/staff/media/': typeof StaffStaffMediaIndexRoute
  '/_staff/staff/$dept/calendar/$id': typeof StaffStaffDeptCalendarIdRoute
  '/_staff/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/_staff/staff/$dept/contacts/$id': typeof StaffStaffDeptContactsIdRoute
  '/_staff/staff/$dept/dashboard/$id': typeof StaffStaffDeptDashboardIdRoute
  '/_staff/staff/$dept/menu/$id': typeof StaffStaffDeptMenuIdRoute
  '/_staff/staff/admin/calendar-kinds/$id': typeof StaffStaffAdminCalendarKindsIdRoute
  '/_staff/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/_staff/staff/$dept/calendar/': typeof StaffStaffDeptCalendarIndexRoute
  '/_staff/staff/$dept/categories/': typeof StaffStaffDeptCategoriesIndexRoute
  '/_staff/staff/$dept/contacts/': typeof StaffStaffDeptContactsIndexRoute
  '/_staff/staff/$dept/menu/': typeof StaffStaffDeptMenuIndexRoute
  '/_staff/staff/admin/calendar-kinds/': typeof StaffStaffAdminCalendarKindsIndexRoute
  '/_staff/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/me'
    | '/$slug'
    | '/calendar'
    | '/forbidden'
    | '/login-error'
    | '/search'
    | '/documents/$slug'
    | '/news/$slug'
    | '/staff/content'
    | '/staff/links'
    | '/staff/media'
    | '/documents/'
    | '/news/'
    | '/staff/'
    | '/staff/$dept/calendar'
    | '/staff/$dept/categories'
    | '/staff/$dept/contacts'
    | '/staff/$dept/menu'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/permissions'
    | '/staff/admin/ui-kit'
    | '/staff/content/$id'
    | '/staff/links/$id'
    | '/staff/media/$id'
    | '/staff/$dept/'
    | '/staff/content/'
    | '/staff/links/'
    | '/staff/media/'
    | '/staff/$dept/calendar/$id'
    | '/staff/$dept/categories/$id'
    | '/staff/$dept/contacts/$id'
    | '/staff/$dept/dashboard/$id'
    | '/staff/$dept/menu/$id'
    | '/staff/admin/calendar-kinds/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/calendar/'
    | '/staff/$dept/categories/'
    | '/staff/$dept/contacts/'
    | '/staff/$dept/menu/'
    | '/staff/admin/calendar-kinds/'
    | '/staff/admin/permissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/me'
    | '/$slug'
    | '/calendar'
    | '/forbidden'
    | '/login-error'
    | '/search'
    | '/documents/$slug'
    | '/news/$slug'
    | '/documents'
    | '/news'
    | '/staff'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/ui-kit'
    | '/staff/content/$id'
    | '/staff/links/$id'
    | '/staff/media/$id'
    | '/staff/$dept'
    | '/staff/content'
    | '/staff/links'
    | '/staff/media'
    | '/staff/$dept/calendar/$id'
    | '/staff/$dept/categories/$id'
    | '/staff/$dept/contacts/$id'
    | '/staff/$dept/dashboard/$id'
    | '/staff/$dept/menu/$id'
    | '/staff/admin/calendar-kinds/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/calendar'
    | '/staff/$dept/categories'
    | '/staff/$dept/contacts'
    | '/staff/$dept/menu'
    | '/staff/admin/calendar-kinds'
    | '/staff/admin/permissions'
  id:
    | '__root__'
    | '/_member'
    | '/_public'
    | '/_staff'
    | '/_member/contact'
    | '/_member/me'
    | '/_public/$slug'
    | '/_public/calendar'
    | '/_public/forbidden'
    | '/_public/login-error'
    | '/_public/search'
    | '/_public/'
    | '/_public/documents/$slug'
    | '/_public/news/$slug'
    | '/_staff/staff/content'
    | '/_staff/staff/links'
    | '/_staff/staff/media'
    | '/_public/documents/'
    | '/_public/news/'
    | '/_staff/staff/'
    | '/_staff/staff/$dept/calendar'
    | '/_staff/staff/$dept/categories'
    | '/_staff/staff/$dept/contacts'
    | '/_staff/staff/$dept/menu'
    | '/_staff/staff/admin/audit'
    | '/_staff/staff/admin/modules'
    | '/_staff/staff/admin/permissions'
    | '/_staff/staff/admin/ui-kit'
    | '/_staff/staff/content/$id'
    | '/_staff/staff/links/$id'
    | '/_staff/staff/media/$id'
    | '/_staff/staff/$dept/'
    | '/_staff/staff/content/'
    | '/_staff/staff/links/'
    | '/_staff/staff/media/'
    | '/_staff/staff/$dept/calendar/$id'
    | '/_staff/staff/$dept/categories/$id'
    | '/_staff/staff/$dept/contacts/$id'
    | '/_staff/staff/$dept/dashboard/$id'
    | '/_staff/staff/$dept/menu/$id'
    | '/_staff/staff/admin/calendar-kinds/$id'
    | '/_staff/staff/admin/permissions/$id'
    | '/_staff/staff/$dept/calendar/'
    | '/_staff/staff/$dept/categories/'
    | '/_staff/staff/$dept/contacts/'
    | '/_staff/staff/$dept/menu/'
    | '/_staff/staff/admin/calendar-kinds/'
    | '/_staff/staff/admin/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/contact': {
      id: '/_member/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MemberContactRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/me': {
      id: '/_member/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MemberMeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$slug': {
      id: '/_public/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/calendar': {
      id: '/_public/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PublicCalendarRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forbidden': {
      id: '/_public/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PublicForbiddenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login-error': {
      id: '/_public/login-error'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof PublicLoginErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents/': {
      id: '/_public/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof PublicDocumentsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents/$slug': {
      id: '/_public/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof PublicDocumentsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_staff/staff/': {
      id: '/_staff/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffStaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/content': {
      id: '/_staff/staff/content'
      path: '/staff/content'
      fullPath: '/staff/content'
      preLoaderRoute: typeof StaffStaffContentRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/links': {
      id: '/_staff/staff/links'
      path: '/staff/links'
      fullPath: '/staff/links'
      preLoaderRoute: typeof StaffStaffLinksRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/media': {
      id: '/_staff/staff/media'
      path: '/staff/media'
      fullPath: '/staff/media'
      preLoaderRoute: typeof StaffStaffMediaRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/': {
      id: '/_staff/staff/$dept/'
      path: '/staff/$dept'
      fullPath: '/staff/$dept/'
      preLoaderRoute: typeof StaffStaffDeptIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/calendar': {
      id: '/_staff/staff/$dept/calendar'
      path: '/staff/$dept/calendar'
      fullPath: '/staff/$dept/calendar'
      preLoaderRoute: typeof StaffStaffDeptCalendarRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/categories': {
      id: '/_staff/staff/$dept/categories'
      path: '/staff/$dept/categories'
      fullPath: '/staff/$dept/categories'
      preLoaderRoute: typeof StaffStaffDeptCategoriesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/contacts': {
      id: '/_staff/staff/$dept/contacts'
      path: '/staff/$dept/contacts'
      fullPath: '/staff/$dept/contacts'
      preLoaderRoute: typeof StaffStaffDeptContactsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/menu': {
      id: '/_staff/staff/$dept/menu'
      path: '/staff/$dept/menu'
      fullPath: '/staff/$dept/menu'
      preLoaderRoute: typeof StaffStaffDeptMenuRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/audit': {
      id: '/_staff/staff/admin/audit'
      path: '/staff/admin/audit'
      fullPath: '/staff/admin/audit'
      preLoaderRoute: typeof StaffStaffAdminAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/modules': {
      id: '/_staff/staff/admin/modules'
      path: '/staff/admin/modules'
      fullPath: '/staff/admin/modules'
      preLoaderRoute: typeof StaffStaffAdminModulesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/permissions': {
      id: '/_staff/staff/admin/permissions'
      path: '/staff/admin/permissions'
      fullPath: '/staff/admin/permissions'
      preLoaderRoute: typeof StaffStaffAdminPermissionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/ui-kit': {
      id: '/_staff/staff/admin/ui-kit'
      path: '/staff/admin/ui-kit'
      fullPath: '/staff/admin/ui-kit'
      preLoaderRoute: typeof StaffStaffAdminUiKitRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/content/': {
      id: '/_staff/staff/content/'
      path: '/'
      fullPath: '/staff/content/'
      preLoaderRoute: typeof StaffStaffContentIndexRouteImport
      parentRoute: typeof StaffStaffContentRoute
    }
    '/_staff/staff/content/$id': {
      id: '/_staff/staff/content/$id'
      path: '/$id'
      fullPath: '/staff/content/$id'
      preLoaderRoute: typeof StaffStaffContentIdRouteImport
      parentRoute: typeof StaffStaffContentRoute
    }
    '/_staff/staff/links/': {
      id: '/_staff/staff/links/'
      path: '/'
      fullPath: '/staff/links/'
      preLoaderRoute: typeof StaffStaffLinksIndexRouteImport
      parentRoute: typeof StaffStaffLinksRoute
    }
    '/_staff/staff/links/$id': {
      id: '/_staff/staff/links/$id'
      path: '/$id'
      fullPath: '/staff/links/$id'
      preLoaderRoute: typeof StaffStaffLinksIdRouteImport
      parentRoute: typeof StaffStaffLinksRoute
    }
    '/_staff/staff/media/': {
      id: '/_staff/staff/media/'
      path: '/'
      fullPath: '/staff/media/'
      preLoaderRoute: typeof StaffStaffMediaIndexRouteImport
      parentRoute: typeof StaffStaffMediaRoute
    }
    '/_staff/staff/media/$id': {
      id: '/_staff/staff/media/$id'
      path: '/$id'
      fullPath: '/staff/media/$id'
      preLoaderRoute: typeof StaffStaffMediaIdRouteImport
      parentRoute: typeof StaffStaffMediaRoute
    }
    '/_staff/staff/$dept/calendar/': {
      id: '/_staff/staff/$dept/calendar/'
      path: '/'
      fullPath: '/staff/$dept/calendar/'
      preLoaderRoute: typeof StaffStaffDeptCalendarIndexRouteImport
      parentRoute: typeof StaffStaffDeptCalendarRoute
    }
    '/_staff/staff/$dept/calendar/$id': {
      id: '/_staff/staff/$dept/calendar/$id'
      path: '/$id'
      fullPath: '/staff/$dept/calendar/$id'
      preLoaderRoute: typeof StaffStaffDeptCalendarIdRouteImport
      parentRoute: typeof StaffStaffDeptCalendarRoute
    }
    '/_staff/staff/$dept/categories/': {
      id: '/_staff/staff/$dept/categories/'
      path: '/'
      fullPath: '/staff/$dept/categories/'
      preLoaderRoute: typeof StaffStaffDeptCategoriesIndexRouteImport
      parentRoute: typeof StaffStaffDeptCategoriesRoute
    }
    '/_staff/staff/$dept/categories/$id': {
      id: '/_staff/staff/$dept/categories/$id'
      path: '/$id'
      fullPath: '/staff/$dept/categories/$id'
      preLoaderRoute: typeof StaffStaffDeptCategoriesIdRouteImport
      parentRoute: typeof StaffStaffDeptCategoriesRoute
    }
    '/_staff/staff/$dept/contacts/': {
      id: '/_staff/staff/$dept/contacts/'
      path: '/'
      fullPath: '/staff/$dept/contacts/'
      preLoaderRoute: typeof StaffStaffDeptContactsIndexRouteImport
      parentRoute: typeof StaffStaffDeptContactsRoute
    }
    '/_staff/staff/$dept/contacts/$id': {
      id: '/_staff/staff/$dept/contacts/$id'
      path: '/$id'
      fullPath: '/staff/$dept/contacts/$id'
      preLoaderRoute: typeof StaffStaffDeptContactsIdRouteImport
      parentRoute: typeof StaffStaffDeptContactsRoute
    }
    '/_staff/staff/$dept/dashboard/$id': {
      id: '/_staff/staff/$dept/dashboard/$id'
      path: '/staff/$dept/dashboard/$id'
      fullPath: '/staff/$dept/dashboard/$id'
      preLoaderRoute: typeof StaffStaffDeptDashboardIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/menu/': {
      id: '/_staff/staff/$dept/menu/'
      path: '/'
      fullPath: '/staff/$dept/menu/'
      preLoaderRoute: typeof StaffStaffDeptMenuIndexRouteImport
      parentRoute: typeof StaffStaffDeptMenuRoute
    }
    '/_staff/staff/$dept/menu/$id': {
      id: '/_staff/staff/$dept/menu/$id'
      path: '/$id'
      fullPath: '/staff/$dept/menu/$id'
      preLoaderRoute: typeof StaffStaffDeptMenuIdRouteImport
      parentRoute: typeof StaffStaffDeptMenuRoute
    }
    '/_staff/staff/admin/calendar-kinds/': {
      id: '/_staff/staff/admin/calendar-kinds/'
      path: '/staff/admin/calendar-kinds'
      fullPath: '/staff/admin/calendar-kinds/'
      preLoaderRoute: typeof StaffStaffAdminCalendarKindsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/calendar-kinds/$id': {
      id: '/_staff/staff/admin/calendar-kinds/$id'
      path: '/staff/admin/calendar-kinds/$id'
      fullPath: '/staff/admin/calendar-kinds/$id'
      preLoaderRoute: typeof StaffStaffAdminCalendarKindsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/permissions/': {
      id: '/_staff/staff/admin/permissions/'
      path: '/'
      fullPath: '/staff/admin/permissions/'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIndexRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
    '/_staff/staff/admin/permissions/$id': {
      id: '/_staff/staff/admin/permissions/$id'
      path: '/$id'
      fullPath: '/staff/admin/permissions/$id'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIdRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
  }
}

interface MemberRouteChildren {
  MemberContactRoute: typeof MemberContactRoute
  MemberMeRoute: typeof MemberMeRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberContactRoute: MemberContactRoute,
  MemberMeRoute: MemberMeRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PublicRouteChildren {
  PublicSlugRoute: typeof PublicSlugRoute
  PublicCalendarRoute: typeof PublicCalendarRoute
  PublicForbiddenRoute: typeof PublicForbiddenRoute
  PublicLoginErrorRoute: typeof PublicLoginErrorRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDocumentsSlugRoute: typeof PublicDocumentsSlugRoute
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
  PublicDocumentsIndexRoute: typeof PublicDocumentsIndexRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSlugRoute: PublicSlugRoute,
  PublicCalendarRoute: PublicCalendarRoute,
  PublicForbiddenRoute: PublicForbiddenRoute,
  PublicLoginErrorRoute: PublicLoginErrorRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDocumentsSlugRoute: PublicDocumentsSlugRoute,
  PublicNewsSlugRoute: PublicNewsSlugRoute,
  PublicDocumentsIndexRoute: PublicDocumentsIndexRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface StaffStaffContentRouteChildren {
  StaffStaffContentIdRoute: typeof StaffStaffContentIdRoute
  StaffStaffContentIndexRoute: typeof StaffStaffContentIndexRoute
}

const StaffStaffContentRouteChildren: StaffStaffContentRouteChildren = {
  StaffStaffContentIdRoute: StaffStaffContentIdRoute,
  StaffStaffContentIndexRoute: StaffStaffContentIndexRoute,
}

const StaffStaffContentRouteWithChildren =
  StaffStaffContentRoute._addFileChildren(StaffStaffContentRouteChildren)

interface StaffStaffLinksRouteChildren {
  StaffStaffLinksIdRoute: typeof StaffStaffLinksIdRoute
  StaffStaffLinksIndexRoute: typeof StaffStaffLinksIndexRoute
}

const StaffStaffLinksRouteChildren: StaffStaffLinksRouteChildren = {
  StaffStaffLinksIdRoute: StaffStaffLinksIdRoute,
  StaffStaffLinksIndexRoute: StaffStaffLinksIndexRoute,
}

const StaffStaffLinksRouteWithChildren = StaffStaffLinksRoute._addFileChildren(
  StaffStaffLinksRouteChildren,
)

interface StaffStaffMediaRouteChildren {
  StaffStaffMediaIdRoute: typeof StaffStaffMediaIdRoute
  StaffStaffMediaIndexRoute: typeof StaffStaffMediaIndexRoute
}

const StaffStaffMediaRouteChildren: StaffStaffMediaRouteChildren = {
  StaffStaffMediaIdRoute: StaffStaffMediaIdRoute,
  StaffStaffMediaIndexRoute: StaffStaffMediaIndexRoute,
}

const StaffStaffMediaRouteWithChildren = StaffStaffMediaRoute._addFileChildren(
  StaffStaffMediaRouteChildren,
)

interface StaffStaffDeptCalendarRouteChildren {
  StaffStaffDeptCalendarIdRoute: typeof StaffStaffDeptCalendarIdRoute
  StaffStaffDeptCalendarIndexRoute: typeof StaffStaffDeptCalendarIndexRoute
}

const StaffStaffDeptCalendarRouteChildren: StaffStaffDeptCalendarRouteChildren =
  {
    StaffStaffDeptCalendarIdRoute: StaffStaffDeptCalendarIdRoute,
    StaffStaffDeptCalendarIndexRoute: StaffStaffDeptCalendarIndexRoute,
  }

const StaffStaffDeptCalendarRouteWithChildren =
  StaffStaffDeptCalendarRoute._addFileChildren(
    StaffStaffDeptCalendarRouteChildren,
  )

interface StaffStaffDeptCategoriesRouteChildren {
  StaffStaffDeptCategoriesIdRoute: typeof StaffStaffDeptCategoriesIdRoute
  StaffStaffDeptCategoriesIndexRoute: typeof StaffStaffDeptCategoriesIndexRoute
}

const StaffStaffDeptCategoriesRouteChildren: StaffStaffDeptCategoriesRouteChildren =
  {
    StaffStaffDeptCategoriesIdRoute: StaffStaffDeptCategoriesIdRoute,
    StaffStaffDeptCategoriesIndexRoute: StaffStaffDeptCategoriesIndexRoute,
  }

const StaffStaffDeptCategoriesRouteWithChildren =
  StaffStaffDeptCategoriesRoute._addFileChildren(
    StaffStaffDeptCategoriesRouteChildren,
  )

interface StaffStaffDeptContactsRouteChildren {
  StaffStaffDeptContactsIdRoute: typeof StaffStaffDeptContactsIdRoute
  StaffStaffDeptContactsIndexRoute: typeof StaffStaffDeptContactsIndexRoute
}

const StaffStaffDeptContactsRouteChildren: StaffStaffDeptContactsRouteChildren =
  {
    StaffStaffDeptContactsIdRoute: StaffStaffDeptContactsIdRoute,
    StaffStaffDeptContactsIndexRoute: StaffStaffDeptContactsIndexRoute,
  }

const StaffStaffDeptContactsRouteWithChildren =
  StaffStaffDeptContactsRoute._addFileChildren(
    StaffStaffDeptContactsRouteChildren,
  )

interface StaffStaffDeptMenuRouteChildren {
  StaffStaffDeptMenuIdRoute: typeof StaffStaffDeptMenuIdRoute
  StaffStaffDeptMenuIndexRoute: typeof StaffStaffDeptMenuIndexRoute
}

const StaffStaffDeptMenuRouteChildren: StaffStaffDeptMenuRouteChildren = {
  StaffStaffDeptMenuIdRoute: StaffStaffDeptMenuIdRoute,
  StaffStaffDeptMenuIndexRoute: StaffStaffDeptMenuIndexRoute,
}

const StaffStaffDeptMenuRouteWithChildren =
  StaffStaffDeptMenuRoute._addFileChildren(StaffStaffDeptMenuRouteChildren)

interface StaffStaffAdminPermissionsRouteChildren {
  StaffStaffAdminPermissionsIdRoute: typeof StaffStaffAdminPermissionsIdRoute
  StaffStaffAdminPermissionsIndexRoute: typeof StaffStaffAdminPermissionsIndexRoute
}

const StaffStaffAdminPermissionsRouteChildren: StaffStaffAdminPermissionsRouteChildren =
  {
    StaffStaffAdminPermissionsIdRoute: StaffStaffAdminPermissionsIdRoute,
    StaffStaffAdminPermissionsIndexRoute: StaffStaffAdminPermissionsIndexRoute,
  }

const StaffStaffAdminPermissionsRouteWithChildren =
  StaffStaffAdminPermissionsRoute._addFileChildren(
    StaffStaffAdminPermissionsRouteChildren,
  )

interface StaffRouteChildren {
  StaffStaffContentRoute: typeof StaffStaffContentRouteWithChildren
  StaffStaffLinksRoute: typeof StaffStaffLinksRouteWithChildren
  StaffStaffMediaRoute: typeof StaffStaffMediaRouteWithChildren
  StaffStaffIndexRoute: typeof StaffStaffIndexRoute
  StaffStaffDeptCalendarRoute: typeof StaffStaffDeptCalendarRouteWithChildren
  StaffStaffDeptCategoriesRoute: typeof StaffStaffDeptCategoriesRouteWithChildren
  StaffStaffDeptContactsRoute: typeof StaffStaffDeptContactsRouteWithChildren
  StaffStaffDeptMenuRoute: typeof StaffStaffDeptMenuRouteWithChildren
  StaffStaffAdminAuditRoute: typeof StaffStaffAdminAuditRoute
  StaffStaffAdminModulesRoute: typeof StaffStaffAdminModulesRoute
  StaffStaffAdminPermissionsRoute: typeof StaffStaffAdminPermissionsRouteWithChildren
  StaffStaffAdminUiKitRoute: typeof StaffStaffAdminUiKitRoute
  StaffStaffDeptIndexRoute: typeof StaffStaffDeptIndexRoute
  StaffStaffDeptDashboardIdRoute: typeof StaffStaffDeptDashboardIdRoute
  StaffStaffAdminCalendarKindsIdRoute: typeof StaffStaffAdminCalendarKindsIdRoute
  StaffStaffAdminCalendarKindsIndexRoute: typeof StaffStaffAdminCalendarKindsIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffContentRoute: StaffStaffContentRouteWithChildren,
  StaffStaffLinksRoute: StaffStaffLinksRouteWithChildren,
  StaffStaffMediaRoute: StaffStaffMediaRouteWithChildren,
  StaffStaffIndexRoute: StaffStaffIndexRoute,
  StaffStaffDeptCalendarRoute: StaffStaffDeptCalendarRouteWithChildren,
  StaffStaffDeptCategoriesRoute: StaffStaffDeptCategoriesRouteWithChildren,
  StaffStaffDeptContactsRoute: StaffStaffDeptContactsRouteWithChildren,
  StaffStaffDeptMenuRoute: StaffStaffDeptMenuRouteWithChildren,
  StaffStaffAdminAuditRoute: StaffStaffAdminAuditRoute,
  StaffStaffAdminModulesRoute: StaffStaffAdminModulesRoute,
  StaffStaffAdminPermissionsRoute: StaffStaffAdminPermissionsRouteWithChildren,
  StaffStaffAdminUiKitRoute: StaffStaffAdminUiKitRoute,
  StaffStaffDeptIndexRoute: StaffStaffDeptIndexRoute,
  StaffStaffDeptDashboardIdRoute: StaffStaffDeptDashboardIdRoute,
  StaffStaffAdminCalendarKindsIdRoute: StaffStaffAdminCalendarKindsIdRoute,
  StaffStaffAdminCalendarKindsIndexRoute:
    StaffStaffAdminCalendarKindsIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
