/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as MemberMeRouteImport } from './routes/_member/me'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSlugRouteImport } from './routes/_public/$slug'
import { Route as PublicForbiddenRouteImport } from './routes/_public/forbidden'
import { Route as PublicLoginErrorRouteImport } from './routes/_public/login-error'
import { Route as StaffStaffIndexRouteImport } from './routes/_staff/staff.index'
import { Route as StaffStaffDeptContentRouteImport } from './routes/_staff/staff.$dept.content'
import { Route as StaffStaffDeptLinksRouteImport } from './routes/_staff/staff.$dept.links'
import { Route as StaffStaffAdminAuditRouteImport } from './routes/_staff/staff.admin.audit'
import { Route as StaffStaffAdminModulesRouteImport } from './routes/_staff/staff.admin.modules'
import { Route as StaffStaffAdminPermissionsRouteImport } from './routes/_staff/staff.admin.permissions'
import { Route as StaffStaffAdminUiKitRouteImport } from './routes/_staff/staff.admin.ui-kit'
import { Route as StaffStaffDeptContentIndexRouteImport } from './routes/_staff/staff.$dept.content.index'
import { Route as StaffStaffDeptContentIdRouteImport } from './routes/_staff/staff.$dept.content.$id'
import { Route as StaffStaffDeptLinksIndexRouteImport } from './routes/_staff/staff.$dept.links.index'
import { Route as StaffStaffDeptLinksIdRouteImport } from './routes/_staff/staff.$dept.links.$id'
import { Route as StaffStaffAdminPermissionsIndexRouteImport } from './routes/_staff/staff.admin.permissions.index'
import { Route as StaffStaffAdminPermissionsIdRouteImport } from './routes/_staff/staff.admin.permissions.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberMeRoute = MemberMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MemberRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForbiddenRoute = PublicForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginErrorRoute = PublicLoginErrorRouteImport.update({
  id: '/login-error',
  path: '/login-error',
  getParentRoute: () => PublicRoute,
} as any)
const StaffStaffIndexRoute = StaffStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptContentRoute = StaffStaffDeptContentRouteImport.update({
  id: '/staff/$dept/content',
  path: '/staff/$dept/content',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptLinksRoute = StaffStaffDeptLinksRouteImport.update({
  id: '/staff/$dept/links',
  path: '/staff/$dept/links',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminAuditRoute = StaffStaffAdminAuditRouteImport.update({
  id: '/staff/admin/audit',
  path: '/staff/admin/audit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminModulesRoute = StaffStaffAdminModulesRouteImport.update({
  id: '/staff/admin/modules',
  path: '/staff/admin/modules',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminPermissionsRoute =
  StaffStaffAdminPermissionsRouteImport.update({
    id: '/staff/admin/permissions',
    path: '/staff/admin/permissions',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffAdminUiKitRoute = StaffStaffAdminUiKitRouteImport.update({
  id: '/staff/admin/ui-kit',
  path: '/staff/admin/ui-kit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptContentIndexRoute =
  StaffStaffDeptContentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptContentRoute,
  } as any)
const StaffStaffDeptContentIdRoute = StaffStaffDeptContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptContentRoute,
} as any)
const StaffStaffDeptLinksIndexRoute =
  StaffStaffDeptLinksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptLinksRoute,
  } as any)
const StaffStaffDeptLinksIdRoute = StaffStaffDeptLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptLinksRoute,
} as any)
const StaffStaffAdminPermissionsIndexRoute =
  StaffStaffAdminPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)
const StaffStaffAdminPermissionsIdRoute =
  StaffStaffAdminPermissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/staff/': typeof StaffStaffIndexRoute
  '/staff/$dept/content': typeof StaffStaffDeptContentRouteWithChildren
  '/staff/$dept/links': typeof StaffStaffDeptLinksRouteWithChildren
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/content/': typeof StaffStaffDeptContentIndexRoute
  '/staff/$dept/links/': typeof StaffStaffDeptLinksIndexRoute
  '/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/staff': typeof StaffStaffIndexRoute
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/content': typeof StaffStaffDeptContentIndexRoute
  '/staff/$dept/links': typeof StaffStaffDeptLinksIndexRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/_member/me': typeof MemberMeRoute
  '/_public/$slug': typeof PublicSlugRoute
  '/_public/forbidden': typeof PublicForbiddenRoute
  '/_public/login-error': typeof PublicLoginErrorRoute
  '/_public/': typeof PublicIndexRoute
  '/_staff/staff/': typeof StaffStaffIndexRoute
  '/_staff/staff/$dept/content': typeof StaffStaffDeptContentRouteWithChildren
  '/_staff/staff/$dept/links': typeof StaffStaffDeptLinksRouteWithChildren
  '/_staff/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/_staff/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/_staff/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/_staff/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/_staff/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/_staff/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/_staff/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/_staff/staff/$dept/content/': typeof StaffStaffDeptContentIndexRoute
  '/_staff/staff/$dept/links/': typeof StaffStaffDeptLinksIndexRoute
  '/_staff/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/$slug'
    | '/forbidden'
    | '/login-error'
    | '/staff/'
    | '/staff/$dept/content'
    | '/staff/$dept/links'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/permissions'
    | '/staff/admin/ui-kit'
    | '/staff/$dept/content/$id'
    | '/staff/$dept/links/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/content/'
    | '/staff/$dept/links/'
    | '/staff/admin/permissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/$slug'
    | '/forbidden'
    | '/login-error'
    | '/staff'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/ui-kit'
    | '/staff/$dept/content/$id'
    | '/staff/$dept/links/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/content'
    | '/staff/$dept/links'
    | '/staff/admin/permissions'
  id:
    | '__root__'
    | '/_member'
    | '/_public'
    | '/_staff'
    | '/_member/me'
    | '/_public/$slug'
    | '/_public/forbidden'
    | '/_public/login-error'
    | '/_public/'
    | '/_staff/staff/'
    | '/_staff/staff/$dept/content'
    | '/_staff/staff/$dept/links'
    | '/_staff/staff/admin/audit'
    | '/_staff/staff/admin/modules'
    | '/_staff/staff/admin/permissions'
    | '/_staff/staff/admin/ui-kit'
    | '/_staff/staff/$dept/content/$id'
    | '/_staff/staff/$dept/links/$id'
    | '/_staff/staff/admin/permissions/$id'
    | '/_staff/staff/$dept/content/'
    | '/_staff/staff/$dept/links/'
    | '/_staff/staff/admin/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/me': {
      id: '/_member/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MemberMeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$slug': {
      id: '/_public/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forbidden': {
      id: '/_public/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PublicForbiddenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login-error': {
      id: '/_public/login-error'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof PublicLoginErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_staff/staff/': {
      id: '/_staff/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffStaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/content': {
      id: '/_staff/staff/$dept/content'
      path: '/staff/$dept/content'
      fullPath: '/staff/$dept/content'
      preLoaderRoute: typeof StaffStaffDeptContentRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/links': {
      id: '/_staff/staff/$dept/links'
      path: '/staff/$dept/links'
      fullPath: '/staff/$dept/links'
      preLoaderRoute: typeof StaffStaffDeptLinksRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/audit': {
      id: '/_staff/staff/admin/audit'
      path: '/staff/admin/audit'
      fullPath: '/staff/admin/audit'
      preLoaderRoute: typeof StaffStaffAdminAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/modules': {
      id: '/_staff/staff/admin/modules'
      path: '/staff/admin/modules'
      fullPath: '/staff/admin/modules'
      preLoaderRoute: typeof StaffStaffAdminModulesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/permissions': {
      id: '/_staff/staff/admin/permissions'
      path: '/staff/admin/permissions'
      fullPath: '/staff/admin/permissions'
      preLoaderRoute: typeof StaffStaffAdminPermissionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/ui-kit': {
      id: '/_staff/staff/admin/ui-kit'
      path: '/staff/admin/ui-kit'
      fullPath: '/staff/admin/ui-kit'
      preLoaderRoute: typeof StaffStaffAdminUiKitRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/content/': {
      id: '/_staff/staff/$dept/content/'
      path: '/'
      fullPath: '/staff/$dept/content/'
      preLoaderRoute: typeof StaffStaffDeptContentIndexRouteImport
      parentRoute: typeof StaffStaffDeptContentRoute
    }
    '/_staff/staff/$dept/content/$id': {
      id: '/_staff/staff/$dept/content/$id'
      path: '/$id'
      fullPath: '/staff/$dept/content/$id'
      preLoaderRoute: typeof StaffStaffDeptContentIdRouteImport
      parentRoute: typeof StaffStaffDeptContentRoute
    }
    '/_staff/staff/$dept/links/': {
      id: '/_staff/staff/$dept/links/'
      path: '/'
      fullPath: '/staff/$dept/links/'
      preLoaderRoute: typeof StaffStaffDeptLinksIndexRouteImport
      parentRoute: typeof StaffStaffDeptLinksRoute
    }
    '/_staff/staff/$dept/links/$id': {
      id: '/_staff/staff/$dept/links/$id'
      path: '/$id'
      fullPath: '/staff/$dept/links/$id'
      preLoaderRoute: typeof StaffStaffDeptLinksIdRouteImport
      parentRoute: typeof StaffStaffDeptLinksRoute
    }
    '/_staff/staff/admin/permissions/': {
      id: '/_staff/staff/admin/permissions/'
      path: '/'
      fullPath: '/staff/admin/permissions/'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIndexRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
    '/_staff/staff/admin/permissions/$id': {
      id: '/_staff/staff/admin/permissions/$id'
      path: '/$id'
      fullPath: '/staff/admin/permissions/$id'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIdRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
  }
}

interface MemberRouteChildren {
  MemberMeRoute: typeof MemberMeRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberMeRoute: MemberMeRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PublicRouteChildren {
  PublicSlugRoute: typeof PublicSlugRoute
  PublicForbiddenRoute: typeof PublicForbiddenRoute
  PublicLoginErrorRoute: typeof PublicLoginErrorRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSlugRoute: PublicSlugRoute,
  PublicForbiddenRoute: PublicForbiddenRoute,
  PublicLoginErrorRoute: PublicLoginErrorRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface StaffStaffDeptContentRouteChildren {
  StaffStaffDeptContentIdRoute: typeof StaffStaffDeptContentIdRoute
  StaffStaffDeptContentIndexRoute: typeof StaffStaffDeptContentIndexRoute
}

const StaffStaffDeptContentRouteChildren: StaffStaffDeptContentRouteChildren = {
  StaffStaffDeptContentIdRoute: StaffStaffDeptContentIdRoute,
  StaffStaffDeptContentIndexRoute: StaffStaffDeptContentIndexRoute,
}

const StaffStaffDeptContentRouteWithChildren =
  StaffStaffDeptContentRoute._addFileChildren(
    StaffStaffDeptContentRouteChildren,
  )

interface StaffStaffDeptLinksRouteChildren {
  StaffStaffDeptLinksIdRoute: typeof StaffStaffDeptLinksIdRoute
  StaffStaffDeptLinksIndexRoute: typeof StaffStaffDeptLinksIndexRoute
}

const StaffStaffDeptLinksRouteChildren: StaffStaffDeptLinksRouteChildren = {
  StaffStaffDeptLinksIdRoute: StaffStaffDeptLinksIdRoute,
  StaffStaffDeptLinksIndexRoute: StaffStaffDeptLinksIndexRoute,
}

const StaffStaffDeptLinksRouteWithChildren =
  StaffStaffDeptLinksRoute._addFileChildren(StaffStaffDeptLinksRouteChildren)

interface StaffStaffAdminPermissionsRouteChildren {
  StaffStaffAdminPermissionsIdRoute: typeof StaffStaffAdminPermissionsIdRoute
  StaffStaffAdminPermissionsIndexRoute: typeof StaffStaffAdminPermissionsIndexRoute
}

const StaffStaffAdminPermissionsRouteChildren: StaffStaffAdminPermissionsRouteChildren =
  {
    StaffStaffAdminPermissionsIdRoute: StaffStaffAdminPermissionsIdRoute,
    StaffStaffAdminPermissionsIndexRoute: StaffStaffAdminPermissionsIndexRoute,
  }

const StaffStaffAdminPermissionsRouteWithChildren =
  StaffStaffAdminPermissionsRoute._addFileChildren(
    StaffStaffAdminPermissionsRouteChildren,
  )

interface StaffRouteChildren {
  StaffStaffIndexRoute: typeof StaffStaffIndexRoute
  StaffStaffDeptContentRoute: typeof StaffStaffDeptContentRouteWithChildren
  StaffStaffDeptLinksRoute: typeof StaffStaffDeptLinksRouteWithChildren
  StaffStaffAdminAuditRoute: typeof StaffStaffAdminAuditRoute
  StaffStaffAdminModulesRoute: typeof StaffStaffAdminModulesRoute
  StaffStaffAdminPermissionsRoute: typeof StaffStaffAdminPermissionsRouteWithChildren
  StaffStaffAdminUiKitRoute: typeof StaffStaffAdminUiKitRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIndexRoute: StaffStaffIndexRoute,
  StaffStaffDeptContentRoute: StaffStaffDeptContentRouteWithChildren,
  StaffStaffDeptLinksRoute: StaffStaffDeptLinksRouteWithChildren,
  StaffStaffAdminAuditRoute: StaffStaffAdminAuditRoute,
  StaffStaffAdminModulesRoute: StaffStaffAdminModulesRoute,
  StaffStaffAdminPermissionsRoute: StaffStaffAdminPermissionsRouteWithChildren,
  StaffStaffAdminUiKitRoute: StaffStaffAdminUiKitRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
