/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as MemberMeRouteImport } from './routes/_member/me'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSlugRouteImport } from './routes/_public/$slug'
import { Route as PublicForbiddenRouteImport } from './routes/_public/forbidden'
import { Route as PublicLoginErrorRouteImport } from './routes/_public/login-error'
import { Route as PublicDocumentsIndexRouteImport } from './routes/_public/documents.index'
import { Route as PublicDocumentsSlugRouteImport } from './routes/_public/documents.$slug'
import { Route as PublicNewsIndexRouteImport } from './routes/_public/news.index'
import { Route as PublicNewsSlugRouteImport } from './routes/_public/news.$slug'
import { Route as StaffStaffIndexRouteImport } from './routes/_staff/staff.index'
import { Route as StaffStaffDeptCategoriesRouteImport } from './routes/_staff/staff.$dept.categories'
import { Route as StaffStaffDeptContentRouteImport } from './routes/_staff/staff.$dept.content'
import { Route as StaffStaffDeptDocumentsRouteImport } from './routes/_staff/staff.$dept.documents'
import { Route as StaffStaffDeptLinksRouteImport } from './routes/_staff/staff.$dept.links'
import { Route as StaffStaffDeptMediaRouteImport } from './routes/_staff/staff.$dept.media'
import { Route as StaffStaffDeptNewsRouteImport } from './routes/_staff/staff.$dept.news'
import { Route as StaffStaffAdminAuditRouteImport } from './routes/_staff/staff.admin.audit'
import { Route as StaffStaffAdminModulesRouteImport } from './routes/_staff/staff.admin.modules'
import { Route as StaffStaffAdminPermissionsRouteImport } from './routes/_staff/staff.admin.permissions'
import { Route as StaffStaffAdminUiKitRouteImport } from './routes/_staff/staff.admin.ui-kit'
import { Route as StaffStaffDeptCategoriesIndexRouteImport } from './routes/_staff/staff.$dept.categories.index'
import { Route as StaffStaffDeptCategoriesIdRouteImport } from './routes/_staff/staff.$dept.categories.$id'
import { Route as StaffStaffDeptContentIndexRouteImport } from './routes/_staff/staff.$dept.content.index'
import { Route as StaffStaffDeptContentIdRouteImport } from './routes/_staff/staff.$dept.content.$id'
import { Route as StaffStaffDeptDocumentsIndexRouteImport } from './routes/_staff/staff.$dept.documents.index'
import { Route as StaffStaffDeptDocumentsIdRouteImport } from './routes/_staff/staff.$dept.documents.$id'
import { Route as StaffStaffDeptLinksIndexRouteImport } from './routes/_staff/staff.$dept.links.index'
import { Route as StaffStaffDeptLinksIdRouteImport } from './routes/_staff/staff.$dept.links.$id'
import { Route as StaffStaffDeptMediaIndexRouteImport } from './routes/_staff/staff.$dept.media.index'
import { Route as StaffStaffDeptMediaIdRouteImport } from './routes/_staff/staff.$dept.media.$id'
import { Route as StaffStaffDeptNewsIndexRouteImport } from './routes/_staff/staff.$dept.news.index'
import { Route as StaffStaffDeptNewsIdRouteImport } from './routes/_staff/staff.$dept.news.$id'
import { Route as StaffStaffAdminPermissionsIndexRouteImport } from './routes/_staff/staff.admin.permissions.index'
import { Route as StaffStaffAdminPermissionsIdRouteImport } from './routes/_staff/staff.admin.permissions.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberMeRoute = MemberMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MemberRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForbiddenRoute = PublicForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginErrorRoute = PublicLoginErrorRouteImport.update({
  id: '/login-error',
  path: '/login-error',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsIndexRoute = PublicDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsSlugRoute = PublicDocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const StaffStaffIndexRoute = StaffStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptCategoriesRoute =
  StaffStaffDeptCategoriesRouteImport.update({
    id: '/staff/$dept/categories',
    path: '/staff/$dept/categories',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffDeptContentRoute = StaffStaffDeptContentRouteImport.update({
  id: '/staff/$dept/content',
  path: '/staff/$dept/content',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptDocumentsRoute = StaffStaffDeptDocumentsRouteImport.update({
  id: '/staff/$dept/documents',
  path: '/staff/$dept/documents',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptLinksRoute = StaffStaffDeptLinksRouteImport.update({
  id: '/staff/$dept/links',
  path: '/staff/$dept/links',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptMediaRoute = StaffStaffDeptMediaRouteImport.update({
  id: '/staff/$dept/media',
  path: '/staff/$dept/media',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptNewsRoute = StaffStaffDeptNewsRouteImport.update({
  id: '/staff/$dept/news',
  path: '/staff/$dept/news',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminAuditRoute = StaffStaffAdminAuditRouteImport.update({
  id: '/staff/admin/audit',
  path: '/staff/admin/audit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminModulesRoute = StaffStaffAdminModulesRouteImport.update({
  id: '/staff/admin/modules',
  path: '/staff/admin/modules',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffAdminPermissionsRoute =
  StaffStaffAdminPermissionsRouteImport.update({
    id: '/staff/admin/permissions',
    path: '/staff/admin/permissions',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffStaffAdminUiKitRoute = StaffStaffAdminUiKitRouteImport.update({
  id: '/staff/admin/ui-kit',
  path: '/staff/admin/ui-kit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffDeptCategoriesIndexRoute =
  StaffStaffDeptCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptCategoriesRoute,
  } as any)
const StaffStaffDeptCategoriesIdRoute =
  StaffStaffDeptCategoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffDeptCategoriesRoute,
  } as any)
const StaffStaffDeptContentIndexRoute =
  StaffStaffDeptContentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptContentRoute,
  } as any)
const StaffStaffDeptContentIdRoute = StaffStaffDeptContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptContentRoute,
} as any)
const StaffStaffDeptDocumentsIndexRoute =
  StaffStaffDeptDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptDocumentsRoute,
  } as any)
const StaffStaffDeptDocumentsIdRoute =
  StaffStaffDeptDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffDeptDocumentsRoute,
  } as any)
const StaffStaffDeptLinksIndexRoute =
  StaffStaffDeptLinksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptLinksRoute,
  } as any)
const StaffStaffDeptLinksIdRoute = StaffStaffDeptLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptLinksRoute,
} as any)
const StaffStaffDeptMediaIndexRoute =
  StaffStaffDeptMediaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffDeptMediaRoute,
  } as any)
const StaffStaffDeptMediaIdRoute = StaffStaffDeptMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptMediaRoute,
} as any)
const StaffStaffDeptNewsIndexRoute = StaffStaffDeptNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffStaffDeptNewsRoute,
} as any)
const StaffStaffDeptNewsIdRoute = StaffStaffDeptNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffStaffDeptNewsRoute,
} as any)
const StaffStaffAdminPermissionsIndexRoute =
  StaffStaffAdminPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)
const StaffStaffAdminPermissionsIdRoute =
  StaffStaffAdminPermissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StaffStaffAdminPermissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/documents/$slug': typeof PublicDocumentsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/documents/': typeof PublicDocumentsIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/staff/': typeof StaffStaffIndexRoute
  '/staff/$dept/categories': typeof StaffStaffDeptCategoriesRouteWithChildren
  '/staff/$dept/content': typeof StaffStaffDeptContentRouteWithChildren
  '/staff/$dept/documents': typeof StaffStaffDeptDocumentsRouteWithChildren
  '/staff/$dept/links': typeof StaffStaffDeptLinksRouteWithChildren
  '/staff/$dept/media': typeof StaffStaffDeptMediaRouteWithChildren
  '/staff/$dept/news': typeof StaffStaffDeptNewsRouteWithChildren
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/staff/$dept/documents/$id': typeof StaffStaffDeptDocumentsIdRoute
  '/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/staff/$dept/media/$id': typeof StaffStaffDeptMediaIdRoute
  '/staff/$dept/news/$id': typeof StaffStaffDeptNewsIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/categories/': typeof StaffStaffDeptCategoriesIndexRoute
  '/staff/$dept/content/': typeof StaffStaffDeptContentIndexRoute
  '/staff/$dept/documents/': typeof StaffStaffDeptDocumentsIndexRoute
  '/staff/$dept/links/': typeof StaffStaffDeptLinksIndexRoute
  '/staff/$dept/media/': typeof StaffStaffDeptMediaIndexRoute
  '/staff/$dept/news/': typeof StaffStaffDeptNewsIndexRoute
  '/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/me': typeof MemberMeRoute
  '/$slug': typeof PublicSlugRoute
  '/forbidden': typeof PublicForbiddenRoute
  '/login-error': typeof PublicLoginErrorRoute
  '/documents/$slug': typeof PublicDocumentsSlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/documents': typeof PublicDocumentsIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/staff': typeof StaffStaffIndexRoute
  '/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/staff/$dept/documents/$id': typeof StaffStaffDeptDocumentsIdRoute
  '/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/staff/$dept/media/$id': typeof StaffStaffDeptMediaIdRoute
  '/staff/$dept/news/$id': typeof StaffStaffDeptNewsIdRoute
  '/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/staff/$dept/categories': typeof StaffStaffDeptCategoriesIndexRoute
  '/staff/$dept/content': typeof StaffStaffDeptContentIndexRoute
  '/staff/$dept/documents': typeof StaffStaffDeptDocumentsIndexRoute
  '/staff/$dept/links': typeof StaffStaffDeptLinksIndexRoute
  '/staff/$dept/media': typeof StaffStaffDeptMediaIndexRoute
  '/staff/$dept/news': typeof StaffStaffDeptNewsIndexRoute
  '/staff/admin/permissions': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/_member/me': typeof MemberMeRoute
  '/_public/$slug': typeof PublicSlugRoute
  '/_public/forbidden': typeof PublicForbiddenRoute
  '/_public/login-error': typeof PublicLoginErrorRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/documents/$slug': typeof PublicDocumentsSlugRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/_public/documents/': typeof PublicDocumentsIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_staff/staff/': typeof StaffStaffIndexRoute
  '/_staff/staff/$dept/categories': typeof StaffStaffDeptCategoriesRouteWithChildren
  '/_staff/staff/$dept/content': typeof StaffStaffDeptContentRouteWithChildren
  '/_staff/staff/$dept/documents': typeof StaffStaffDeptDocumentsRouteWithChildren
  '/_staff/staff/$dept/links': typeof StaffStaffDeptLinksRouteWithChildren
  '/_staff/staff/$dept/media': typeof StaffStaffDeptMediaRouteWithChildren
  '/_staff/staff/$dept/news': typeof StaffStaffDeptNewsRouteWithChildren
  '/_staff/staff/admin/audit': typeof StaffStaffAdminAuditRoute
  '/_staff/staff/admin/modules': typeof StaffStaffAdminModulesRoute
  '/_staff/staff/admin/permissions': typeof StaffStaffAdminPermissionsRouteWithChildren
  '/_staff/staff/admin/ui-kit': typeof StaffStaffAdminUiKitRoute
  '/_staff/staff/$dept/categories/$id': typeof StaffStaffDeptCategoriesIdRoute
  '/_staff/staff/$dept/content/$id': typeof StaffStaffDeptContentIdRoute
  '/_staff/staff/$dept/documents/$id': typeof StaffStaffDeptDocumentsIdRoute
  '/_staff/staff/$dept/links/$id': typeof StaffStaffDeptLinksIdRoute
  '/_staff/staff/$dept/media/$id': typeof StaffStaffDeptMediaIdRoute
  '/_staff/staff/$dept/news/$id': typeof StaffStaffDeptNewsIdRoute
  '/_staff/staff/admin/permissions/$id': typeof StaffStaffAdminPermissionsIdRoute
  '/_staff/staff/$dept/categories/': typeof StaffStaffDeptCategoriesIndexRoute
  '/_staff/staff/$dept/content/': typeof StaffStaffDeptContentIndexRoute
  '/_staff/staff/$dept/documents/': typeof StaffStaffDeptDocumentsIndexRoute
  '/_staff/staff/$dept/links/': typeof StaffStaffDeptLinksIndexRoute
  '/_staff/staff/$dept/media/': typeof StaffStaffDeptMediaIndexRoute
  '/_staff/staff/$dept/news/': typeof StaffStaffDeptNewsIndexRoute
  '/_staff/staff/admin/permissions/': typeof StaffStaffAdminPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/$slug'
    | '/forbidden'
    | '/login-error'
    | '/documents/$slug'
    | '/news/$slug'
    | '/documents/'
    | '/news/'
    | '/staff/'
    | '/staff/$dept/categories'
    | '/staff/$dept/content'
    | '/staff/$dept/documents'
    | '/staff/$dept/links'
    | '/staff/$dept/media'
    | '/staff/$dept/news'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/permissions'
    | '/staff/admin/ui-kit'
    | '/staff/$dept/categories/$id'
    | '/staff/$dept/content/$id'
    | '/staff/$dept/documents/$id'
    | '/staff/$dept/links/$id'
    | '/staff/$dept/media/$id'
    | '/staff/$dept/news/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/categories/'
    | '/staff/$dept/content/'
    | '/staff/$dept/documents/'
    | '/staff/$dept/links/'
    | '/staff/$dept/media/'
    | '/staff/$dept/news/'
    | '/staff/admin/permissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/$slug'
    | '/forbidden'
    | '/login-error'
    | '/documents/$slug'
    | '/news/$slug'
    | '/documents'
    | '/news'
    | '/staff'
    | '/staff/admin/audit'
    | '/staff/admin/modules'
    | '/staff/admin/ui-kit'
    | '/staff/$dept/categories/$id'
    | '/staff/$dept/content/$id'
    | '/staff/$dept/documents/$id'
    | '/staff/$dept/links/$id'
    | '/staff/$dept/media/$id'
    | '/staff/$dept/news/$id'
    | '/staff/admin/permissions/$id'
    | '/staff/$dept/categories'
    | '/staff/$dept/content'
    | '/staff/$dept/documents'
    | '/staff/$dept/links'
    | '/staff/$dept/media'
    | '/staff/$dept/news'
    | '/staff/admin/permissions'
  id:
    | '__root__'
    | '/_member'
    | '/_public'
    | '/_staff'
    | '/_member/me'
    | '/_public/$slug'
    | '/_public/forbidden'
    | '/_public/login-error'
    | '/_public/'
    | '/_public/documents/$slug'
    | '/_public/news/$slug'
    | '/_public/documents/'
    | '/_public/news/'
    | '/_staff/staff/'
    | '/_staff/staff/$dept/categories'
    | '/_staff/staff/$dept/content'
    | '/_staff/staff/$dept/documents'
    | '/_staff/staff/$dept/links'
    | '/_staff/staff/$dept/media'
    | '/_staff/staff/$dept/news'
    | '/_staff/staff/admin/audit'
    | '/_staff/staff/admin/modules'
    | '/_staff/staff/admin/permissions'
    | '/_staff/staff/admin/ui-kit'
    | '/_staff/staff/$dept/categories/$id'
    | '/_staff/staff/$dept/content/$id'
    | '/_staff/staff/$dept/documents/$id'
    | '/_staff/staff/$dept/links/$id'
    | '/_staff/staff/$dept/media/$id'
    | '/_staff/staff/$dept/news/$id'
    | '/_staff/staff/admin/permissions/$id'
    | '/_staff/staff/$dept/categories/'
    | '/_staff/staff/$dept/content/'
    | '/_staff/staff/$dept/documents/'
    | '/_staff/staff/$dept/links/'
    | '/_staff/staff/$dept/media/'
    | '/_staff/staff/$dept/news/'
    | '/_staff/staff/admin/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/me': {
      id: '/_member/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MemberMeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$slug': {
      id: '/_public/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forbidden': {
      id: '/_public/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PublicForbiddenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login-error': {
      id: '/_public/login-error'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof PublicLoginErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents/': {
      id: '/_public/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof PublicDocumentsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents/$slug': {
      id: '/_public/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof PublicDocumentsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_staff/staff/': {
      id: '/_staff/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffStaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/categories': {
      id: '/_staff/staff/$dept/categories'
      path: '/staff/$dept/categories'
      fullPath: '/staff/$dept/categories'
      preLoaderRoute: typeof StaffStaffDeptCategoriesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/content': {
      id: '/_staff/staff/$dept/content'
      path: '/staff/$dept/content'
      fullPath: '/staff/$dept/content'
      preLoaderRoute: typeof StaffStaffDeptContentRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/documents': {
      id: '/_staff/staff/$dept/documents'
      path: '/staff/$dept/documents'
      fullPath: '/staff/$dept/documents'
      preLoaderRoute: typeof StaffStaffDeptDocumentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/links': {
      id: '/_staff/staff/$dept/links'
      path: '/staff/$dept/links'
      fullPath: '/staff/$dept/links'
      preLoaderRoute: typeof StaffStaffDeptLinksRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/media': {
      id: '/_staff/staff/$dept/media'
      path: '/staff/$dept/media'
      fullPath: '/staff/$dept/media'
      preLoaderRoute: typeof StaffStaffDeptMediaRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/news': {
      id: '/_staff/staff/$dept/news'
      path: '/staff/$dept/news'
      fullPath: '/staff/$dept/news'
      preLoaderRoute: typeof StaffStaffDeptNewsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/audit': {
      id: '/_staff/staff/admin/audit'
      path: '/staff/admin/audit'
      fullPath: '/staff/admin/audit'
      preLoaderRoute: typeof StaffStaffAdminAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/modules': {
      id: '/_staff/staff/admin/modules'
      path: '/staff/admin/modules'
      fullPath: '/staff/admin/modules'
      preLoaderRoute: typeof StaffStaffAdminModulesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/permissions': {
      id: '/_staff/staff/admin/permissions'
      path: '/staff/admin/permissions'
      fullPath: '/staff/admin/permissions'
      preLoaderRoute: typeof StaffStaffAdminPermissionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/admin/ui-kit': {
      id: '/_staff/staff/admin/ui-kit'
      path: '/staff/admin/ui-kit'
      fullPath: '/staff/admin/ui-kit'
      preLoaderRoute: typeof StaffStaffAdminUiKitRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/$dept/categories/': {
      id: '/_staff/staff/$dept/categories/'
      path: '/'
      fullPath: '/staff/$dept/categories/'
      preLoaderRoute: typeof StaffStaffDeptCategoriesIndexRouteImport
      parentRoute: typeof StaffStaffDeptCategoriesRoute
    }
    '/_staff/staff/$dept/categories/$id': {
      id: '/_staff/staff/$dept/categories/$id'
      path: '/$id'
      fullPath: '/staff/$dept/categories/$id'
      preLoaderRoute: typeof StaffStaffDeptCategoriesIdRouteImport
      parentRoute: typeof StaffStaffDeptCategoriesRoute
    }
    '/_staff/staff/$dept/content/': {
      id: '/_staff/staff/$dept/content/'
      path: '/'
      fullPath: '/staff/$dept/content/'
      preLoaderRoute: typeof StaffStaffDeptContentIndexRouteImport
      parentRoute: typeof StaffStaffDeptContentRoute
    }
    '/_staff/staff/$dept/content/$id': {
      id: '/_staff/staff/$dept/content/$id'
      path: '/$id'
      fullPath: '/staff/$dept/content/$id'
      preLoaderRoute: typeof StaffStaffDeptContentIdRouteImport
      parentRoute: typeof StaffStaffDeptContentRoute
    }
    '/_staff/staff/$dept/documents/': {
      id: '/_staff/staff/$dept/documents/'
      path: '/'
      fullPath: '/staff/$dept/documents/'
      preLoaderRoute: typeof StaffStaffDeptDocumentsIndexRouteImport
      parentRoute: typeof StaffStaffDeptDocumentsRoute
    }
    '/_staff/staff/$dept/documents/$id': {
      id: '/_staff/staff/$dept/documents/$id'
      path: '/$id'
      fullPath: '/staff/$dept/documents/$id'
      preLoaderRoute: typeof StaffStaffDeptDocumentsIdRouteImport
      parentRoute: typeof StaffStaffDeptDocumentsRoute
    }
    '/_staff/staff/$dept/links/': {
      id: '/_staff/staff/$dept/links/'
      path: '/'
      fullPath: '/staff/$dept/links/'
      preLoaderRoute: typeof StaffStaffDeptLinksIndexRouteImport
      parentRoute: typeof StaffStaffDeptLinksRoute
    }
    '/_staff/staff/$dept/links/$id': {
      id: '/_staff/staff/$dept/links/$id'
      path: '/$id'
      fullPath: '/staff/$dept/links/$id'
      preLoaderRoute: typeof StaffStaffDeptLinksIdRouteImport
      parentRoute: typeof StaffStaffDeptLinksRoute
    }
    '/_staff/staff/$dept/media/': {
      id: '/_staff/staff/$dept/media/'
      path: '/'
      fullPath: '/staff/$dept/media/'
      preLoaderRoute: typeof StaffStaffDeptMediaIndexRouteImport
      parentRoute: typeof StaffStaffDeptMediaRoute
    }
    '/_staff/staff/$dept/media/$id': {
      id: '/_staff/staff/$dept/media/$id'
      path: '/$id'
      fullPath: '/staff/$dept/media/$id'
      preLoaderRoute: typeof StaffStaffDeptMediaIdRouteImport
      parentRoute: typeof StaffStaffDeptMediaRoute
    }
    '/_staff/staff/$dept/news/': {
      id: '/_staff/staff/$dept/news/'
      path: '/'
      fullPath: '/staff/$dept/news/'
      preLoaderRoute: typeof StaffStaffDeptNewsIndexRouteImport
      parentRoute: typeof StaffStaffDeptNewsRoute
    }
    '/_staff/staff/$dept/news/$id': {
      id: '/_staff/staff/$dept/news/$id'
      path: '/$id'
      fullPath: '/staff/$dept/news/$id'
      preLoaderRoute: typeof StaffStaffDeptNewsIdRouteImport
      parentRoute: typeof StaffStaffDeptNewsRoute
    }
    '/_staff/staff/admin/permissions/': {
      id: '/_staff/staff/admin/permissions/'
      path: '/'
      fullPath: '/staff/admin/permissions/'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIndexRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
    '/_staff/staff/admin/permissions/$id': {
      id: '/_staff/staff/admin/permissions/$id'
      path: '/$id'
      fullPath: '/staff/admin/permissions/$id'
      preLoaderRoute: typeof StaffStaffAdminPermissionsIdRouteImport
      parentRoute: typeof StaffStaffAdminPermissionsRoute
    }
  }
}

interface MemberRouteChildren {
  MemberMeRoute: typeof MemberMeRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberMeRoute: MemberMeRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PublicRouteChildren {
  PublicSlugRoute: typeof PublicSlugRoute
  PublicForbiddenRoute: typeof PublicForbiddenRoute
  PublicLoginErrorRoute: typeof PublicLoginErrorRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDocumentsSlugRoute: typeof PublicDocumentsSlugRoute
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
  PublicDocumentsIndexRoute: typeof PublicDocumentsIndexRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSlugRoute: PublicSlugRoute,
  PublicForbiddenRoute: PublicForbiddenRoute,
  PublicLoginErrorRoute: PublicLoginErrorRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDocumentsSlugRoute: PublicDocumentsSlugRoute,
  PublicNewsSlugRoute: PublicNewsSlugRoute,
  PublicDocumentsIndexRoute: PublicDocumentsIndexRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface StaffStaffDeptCategoriesRouteChildren {
  StaffStaffDeptCategoriesIdRoute: typeof StaffStaffDeptCategoriesIdRoute
  StaffStaffDeptCategoriesIndexRoute: typeof StaffStaffDeptCategoriesIndexRoute
}

const StaffStaffDeptCategoriesRouteChildren: StaffStaffDeptCategoriesRouteChildren =
  {
    StaffStaffDeptCategoriesIdRoute: StaffStaffDeptCategoriesIdRoute,
    StaffStaffDeptCategoriesIndexRoute: StaffStaffDeptCategoriesIndexRoute,
  }

const StaffStaffDeptCategoriesRouteWithChildren =
  StaffStaffDeptCategoriesRoute._addFileChildren(
    StaffStaffDeptCategoriesRouteChildren,
  )

interface StaffStaffDeptContentRouteChildren {
  StaffStaffDeptContentIdRoute: typeof StaffStaffDeptContentIdRoute
  StaffStaffDeptContentIndexRoute: typeof StaffStaffDeptContentIndexRoute
}

const StaffStaffDeptContentRouteChildren: StaffStaffDeptContentRouteChildren = {
  StaffStaffDeptContentIdRoute: StaffStaffDeptContentIdRoute,
  StaffStaffDeptContentIndexRoute: StaffStaffDeptContentIndexRoute,
}

const StaffStaffDeptContentRouteWithChildren =
  StaffStaffDeptContentRoute._addFileChildren(
    StaffStaffDeptContentRouteChildren,
  )

interface StaffStaffDeptDocumentsRouteChildren {
  StaffStaffDeptDocumentsIdRoute: typeof StaffStaffDeptDocumentsIdRoute
  StaffStaffDeptDocumentsIndexRoute: typeof StaffStaffDeptDocumentsIndexRoute
}

const StaffStaffDeptDocumentsRouteChildren: StaffStaffDeptDocumentsRouteChildren =
  {
    StaffStaffDeptDocumentsIdRoute: StaffStaffDeptDocumentsIdRoute,
    StaffStaffDeptDocumentsIndexRoute: StaffStaffDeptDocumentsIndexRoute,
  }

const StaffStaffDeptDocumentsRouteWithChildren =
  StaffStaffDeptDocumentsRoute._addFileChildren(
    StaffStaffDeptDocumentsRouteChildren,
  )

interface StaffStaffDeptLinksRouteChildren {
  StaffStaffDeptLinksIdRoute: typeof StaffStaffDeptLinksIdRoute
  StaffStaffDeptLinksIndexRoute: typeof StaffStaffDeptLinksIndexRoute
}

const StaffStaffDeptLinksRouteChildren: StaffStaffDeptLinksRouteChildren = {
  StaffStaffDeptLinksIdRoute: StaffStaffDeptLinksIdRoute,
  StaffStaffDeptLinksIndexRoute: StaffStaffDeptLinksIndexRoute,
}

const StaffStaffDeptLinksRouteWithChildren =
  StaffStaffDeptLinksRoute._addFileChildren(StaffStaffDeptLinksRouteChildren)

interface StaffStaffDeptMediaRouteChildren {
  StaffStaffDeptMediaIdRoute: typeof StaffStaffDeptMediaIdRoute
  StaffStaffDeptMediaIndexRoute: typeof StaffStaffDeptMediaIndexRoute
}

const StaffStaffDeptMediaRouteChildren: StaffStaffDeptMediaRouteChildren = {
  StaffStaffDeptMediaIdRoute: StaffStaffDeptMediaIdRoute,
  StaffStaffDeptMediaIndexRoute: StaffStaffDeptMediaIndexRoute,
}

const StaffStaffDeptMediaRouteWithChildren =
  StaffStaffDeptMediaRoute._addFileChildren(StaffStaffDeptMediaRouteChildren)

interface StaffStaffDeptNewsRouteChildren {
  StaffStaffDeptNewsIdRoute: typeof StaffStaffDeptNewsIdRoute
  StaffStaffDeptNewsIndexRoute: typeof StaffStaffDeptNewsIndexRoute
}

const StaffStaffDeptNewsRouteChildren: StaffStaffDeptNewsRouteChildren = {
  StaffStaffDeptNewsIdRoute: StaffStaffDeptNewsIdRoute,
  StaffStaffDeptNewsIndexRoute: StaffStaffDeptNewsIndexRoute,
}

const StaffStaffDeptNewsRouteWithChildren =
  StaffStaffDeptNewsRoute._addFileChildren(StaffStaffDeptNewsRouteChildren)

interface StaffStaffAdminPermissionsRouteChildren {
  StaffStaffAdminPermissionsIdRoute: typeof StaffStaffAdminPermissionsIdRoute
  StaffStaffAdminPermissionsIndexRoute: typeof StaffStaffAdminPermissionsIndexRoute
}

const StaffStaffAdminPermissionsRouteChildren: StaffStaffAdminPermissionsRouteChildren =
  {
    StaffStaffAdminPermissionsIdRoute: StaffStaffAdminPermissionsIdRoute,
    StaffStaffAdminPermissionsIndexRoute: StaffStaffAdminPermissionsIndexRoute,
  }

const StaffStaffAdminPermissionsRouteWithChildren =
  StaffStaffAdminPermissionsRoute._addFileChildren(
    StaffStaffAdminPermissionsRouteChildren,
  )

interface StaffRouteChildren {
  StaffStaffIndexRoute: typeof StaffStaffIndexRoute
  StaffStaffDeptCategoriesRoute: typeof StaffStaffDeptCategoriesRouteWithChildren
  StaffStaffDeptContentRoute: typeof StaffStaffDeptContentRouteWithChildren
  StaffStaffDeptDocumentsRoute: typeof StaffStaffDeptDocumentsRouteWithChildren
  StaffStaffDeptLinksRoute: typeof StaffStaffDeptLinksRouteWithChildren
  StaffStaffDeptMediaRoute: typeof StaffStaffDeptMediaRouteWithChildren
  StaffStaffDeptNewsRoute: typeof StaffStaffDeptNewsRouteWithChildren
  StaffStaffAdminAuditRoute: typeof StaffStaffAdminAuditRoute
  StaffStaffAdminModulesRoute: typeof StaffStaffAdminModulesRoute
  StaffStaffAdminPermissionsRoute: typeof StaffStaffAdminPermissionsRouteWithChildren
  StaffStaffAdminUiKitRoute: typeof StaffStaffAdminUiKitRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIndexRoute: StaffStaffIndexRoute,
  StaffStaffDeptCategoriesRoute: StaffStaffDeptCategoriesRouteWithChildren,
  StaffStaffDeptContentRoute: StaffStaffDeptContentRouteWithChildren,
  StaffStaffDeptDocumentsRoute: StaffStaffDeptDocumentsRouteWithChildren,
  StaffStaffDeptLinksRoute: StaffStaffDeptLinksRouteWithChildren,
  StaffStaffDeptMediaRoute: StaffStaffDeptMediaRouteWithChildren,
  StaffStaffDeptNewsRoute: StaffStaffDeptNewsRouteWithChildren,
  StaffStaffAdminAuditRoute: StaffStaffAdminAuditRoute,
  StaffStaffAdminModulesRoute: StaffStaffAdminModulesRoute,
  StaffStaffAdminPermissionsRoute: StaffStaffAdminPermissionsRouteWithChildren,
  StaffStaffAdminUiKitRoute: StaffStaffAdminUiKitRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
